snowflakedb/gosnowflake

- benchmark/largesetresult/.gitignore
- benchmark/largesetresult/Makefile
- benchmark/largesetresult/largesetresult_test.go
- driver_test.go
- rows.go
- version.go
Improved memory usage by Json decoder instead of a byte array for large result set download
> Improved memory usage by Json decoder instead of a byte array for large result set download

- .gitignore
- cmd/selectmany/.gitignore
A `selectmany` binary was incorrectly committed, because of a glitch in the tool's `.gitignore`. This PR removes it, also adding entries for each cmd to the main `.gitignore` file.
> Remove committed binary and fix .gitignore definitions

- connection.go
left and right handside of the comparison are identical. These types of typos/errors are easily be spotted with a static analyzer.
What do you think about adding such a tool to CI?
> Fix checking the identical errors

- .travis.yml
- benchmark/largesetresult/largesetresult.go
For some reason, the latest Go, aka, tip on Travis, complains no no-test error in the benchmark tests. Obviously no no-test for benchmark, but `go build` runs in the directory and raise the error.
This additional patch is workaround. No impact to the driver itself.
> Fix no no test in the latest Go

- cmd/noconnpool/.gitignore
- cmd/noconnpool/Makefile
- cmd/noconnpool/noconnpool.go
`nonconnpool` demonstrates how to guarantee USE <object type> <object name> changes the current working object and subsequent commands have the access. Since Golang SQL creates a connection pool by default, if you run multiple commands/SQL, each may run on separate sessions. By setting the pool size to 1, it guarantees all commands on the same session.
> Added no connection pool example

- doc.go
- driver.go
- dsn.go
- ocsp.go
- restful.go
- util.go
- util_test.go
Fixed #125 
The environment variables should e used. HTTP_PROXY, HTTPS_PROXY and NO_PROXY
> Removed proxy parameters. 

- driver_test.go
The returned rows from Query method should be closed or the connection is leaked.
> fixed connection leaks by ensuring close the returned row.

- connection.go
- query.go
- retry.go
- rows.go
As the new server release 2.23 started enforcing a signature of key to fetch result set from AWS S3, the client should specify it in the header. Both signature and key are provided by the server already.
> Fixed HTTP 403 errors when getting results from AWS S3.

- converter.go
- driver_test.go
Fixed #132 . Nil (NULL) is not properly.
> NULL was not fetched properly

- auth.go
- authokta.go
- driver.go
- driver_test.go
- ocsp.go
- restful.go
- restful_test.go
- retry.go
- retry_test.go
- rows.go
Raise HTTP 403 error immediately if Snowflake authentication fails.
By default, Snowflake retries HTTP connections for the given timeout to mitigate connection stability issue. HTTP 502 and 504 are the common ones that the Snowflake clients must retry, and sometimes AWS S3 connections return HTTP 4XX and retry helps. That's main reason behind.
However you may not get HTTP 403 immediately for an invalid url as the Go driver doesn't distinguish valid and intermittent errors.
This fix is to mitigate the situation where HTTP 403 is raised immediately only when Snowflake authentication fails.
> raise HTTP 403 immediately if Snowflake authentication fails

- errors.go
Fixed the error message includes returns `URL: %!v(MISSING)`.
> fixed vararg error

- benchmark/largesetresult/largesetresult_test.go
- cmd/selectmany/selectmany.go
- dsn.go
- rows.go
Detach chunk loader memory after used so that GC may reclaim the memory. However it is not guaranteed that GC will run right after it is detached but usually in 5 min. In my experiments, the memory is freed after 3~4 minutes. In order to force to remove the memory, the applications may call `debug.FreeOSMemory`.
> Detach chunk dowloader memory alter used

- CHANGELOG.md
- version.go
- Fixed memory leak in the large result set. The chunk of memory is freed as soon as the cursor moved forward.
- Removed glide dependency in favor of dep #149 (@tjj5036)
- Fixed username and password URL escape issue
- Added Go 1.10 test.
> Bumping up version to 1.1.6

- cmd/oauth/oauth.go
- dsn.go
- dsn_test.go
Removes the restriction that username be present in the DSN when using the OAuth Authenticator. Added a test to verify that a DSN without the username / password works in dsn_test.go.
> Removes the username restriction when using the OAuth Authenticator

- gosnowflake.mak
> not run megacache on Go1.8

- CHANGELOG.md
- doc.go
Updating the doc saying region is deprecated. The parameter started confusion when the subdomain started having more than a region. Instead, `account` parameter will take everything before `snowflakecomputing.com`.
> Deprecate region parameter

- driver_test.go
- dsn.go
- restful.go
This PR intentions to address requirements presented in PR#193 including: 
1. Address documentations for time out explain
2. Enable configuration for RequestTimeout for result polling. Previously if we success on issuing a query but fail on one of the result chunk polling, the driver would retry forever even if the customer set the `requestTimeout` to be some finite number.
It has also shorten the network Client timeout.
> Timeout fix

- auth.go
- driver_test.go
- heartbeat.go
- restful.go
- retry.go
- retry_test.go
For debugging reason, we want to generate an retry id every time we resend to server
> Implement retryIDReplacer and add test cases.

- restful.go
- rows.go
This is a followup PR related to the recent timeout and leaked goroutine fixes. Just patching up more places where the configured `RequestTimeout` isn't used.
> Respect RequestTimeout in more places

- driver_test.go
- rows_test.go
PR #196 add in some configurable timeout value into the code and that leads to segfault in some test cases.
This PR fix those segfaults.
> Fix segfault led by configurable timeout.

- driver_test.go
- dsn.go
- restful.go
- retry.go
- rows.go
**Main Goal: Go-routine elimination**
This PR mainly tries to remove some of the unnecessary go routine in our code base to avoid go routine launching overhead.
**Sub Goal: correct context cancel/timeout handling**
There is a bug identified and fixed when trying to approaching the main goal of this PR: the context cancel/timeout is not handled correctly and therefore could lead to go-routine leak before the go-routine elimination, or infinite loop after the main goal is achieved.
> Remove unnecessary go routine and fix context cancel/timeout handling

- retry.go
Rather than unconditionally sleeping during retry, the wait code should select on 1) the timer and 2) the context. This way a large `sleepTime` doesn't interfere with a higher-level context timeout.
> do not sleep through a context timeout

- .travis.yml
Currently the test for golang v1.8 is failing due to installing golint. The error message is as:
```
go get golang.org/x/lint/golint
../../../golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
make: *** [setup] Error 2
```
Disabled the test for 1.8 for now to unblock Release.
> disable Travis test for golang v1.8

- datatype.go
- debug.go
- release.go
A new parameter 'type' is added on the server side. This PR align driver to that change.
Also, for backward compatibility, the panic would only thrown when sfdebug tag is on. Otherwise the unknown parameter would be attached to the `Unknown` field.
> Handle extra snowflake parameter 'type'

- .travis.yml
go 1.11.x for testing on latest update on Golang.
> Add new 1.11.x for testing

- restful.go
Fix SNOW-60883: https://snowflakecomputing.atlassian.net/browse/SNOW-60883
> Observe has identified a potential defect in GoDriver.
> 
> panic: runtime error: invalid memory address or nil pointer dereference recovered
> panic: runtime error: invalid memory address or nil pointer dereference signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xacd57b
> 
> goroutine 64 running: observe/load/snowflake.(*snowflakeInserter).Insert.func1(0xc00018d4d0, 0xc001eaba78, 0xc00036d280, 0xc00018cea0) 
> /home/dev/observe/code/go/src/observe/load/snowflake/snowflake_inserter.go:57 +0x263
> panic(0xc470c0, 0x1463360) /usr/local/src/runtime/panic.go:513 +0x1b9 
> observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xeb7b80, 0xc00018cb70, 0xc000422c40, 0xc001e745a0, …
> Perform check on error for pingpong response.

- chunk.go
- chunk_test.go
This fixes a logic bug in the custom json parser's buffer management code. It also includes a test case to expose the original bug.
AFAIK this fixes #209, since we hit a similar issue when downloading a large number of rows, patched our fork, and saw the issue go away.
> Fix Custom Json Parser

- driver_test.go
The behavior of SELECT 0000-00-00::DATE has changed due to server side change. Disable the test case given that the change is not finalized yet.
See https://snowflakecomputing.atlassian.net/browse/SNOW-66957 for detail.
> SNOW-69546 disable 0000-00-00 date test

- .travis.yml
Disabling tip test for now to mitigate megacache issue on go dev version.
> Disabling tip test for now

- connection.go
- connection_test.go
- driver.go
Add SERVICE_NAME support by leveraging parameter field. Unit test is added in connection_test.go
> SNOW-66129 Add SERVICE_NAME support to Golang

- converter.go
- converter_test.go
- driver_test.go
This is a redo for #218 with some end to end test case added: 
With #218 the test case would fail on machines in a timezone other than UTC/GMT
> Fixing TIMESTAMP_LTZ serialization issues + Add test case

- connection.go
- connection_test.go
- errors.go
We already ignore whatever error returned from CloseSession(). Add a mock test to address it.
> Add test case to address ignoring Session Gone

- auth.go
- auth_test.go
- authokta.go
- authokta_test.go
- cmd/externalbrowser/externalbrowser.go
- driver.go
- dsn.go
- dsn_test.go
- errors.go
- priv_key_test.go
- restful.go
This PR is from #228, where a previous change mix the okta URL and the okta type.
To avoid having this issue again, I refactor the code to separate an authenticator and the okta url stored internally.
> Fix okta authentication

- driver_test.go
> SNOW-83424: Disabled TestValidateDatabaseParameter temporarily

- doc.go
- dsn.go
- dsn_test.go
- errors.go
Use account to parse global URL
> snow-81842 Use Standard Connection Fields for Global URL

- .travis.yml
- driver_test.go
- gosnowflake.mak
The following changes would enable CI for the old driver test v1.1.0:
1. Remove lint and mega check as these tools are invalid
2. Remove 0 timestamp test as the behavior already changed;
3. Remove session timezone as the parameter schema has changed;
4. Remove check on connection parameters as the server behavior has changed recently;
> Modify build script and test cases 

- ocsp.go
- ocsp_test.go
There is a size gap between response and overall certificate chain when the chain contains root CA, leading to our code letting go revoked certificate.
https://snowflakecomputing.atlassian.net/browse/SNOW-90763
> Fail open fix

- auth.go
Refine the userAgent field as connector_name/connector_version/language_implementation/language_version/os-platform_info
> SNOW-86744 Add client information to USER-AGENT HTTP header

- connection.go
- connection_test.go
- driver_ocsp_test.go
- restful.go
- restful_test.go
Reuse the same requestID after session token is renewed.
> SNOW-92880: Reuse the same requestID after session token is renewed.

- driver_ocsp_test.go
- ocsp.go
SNOW-96716: add SF_OCSP_RESPONSE_CACHE_DIR environment variiable to specify the OCSP response cache location
> SNOW-96716: add SF_OCSP_RESPONSE_CACHE_DIR environment variiable to specify the OCSP response cache location

- Gopkg.lock
- driver_test.go
- query.go
- rows.go
When there is a precision value for a time or timestamp column, a user is now able to retrieve that value using the ColumnTypes() function. A test created in driver_test.go confirms that it works.
> time precision is returned in ColumnTypes()

- doc.go
- driver_ocsp_test.go
- dsn.go
- dsn_test.go
SNOW-121930: ensure the new URL pattern, i.e., org-account.snowflakecomputing.com, works
Resurrected Global URL support. For some reason, the previous change was not included in the main branch.
> Snow 121930

- doc.go
I do not mention any go library to use to decrypt PKCS8 key since we don't want to give an impression to the user that the library's security level is validated by Snowflake.
> SNOW-127316 Add doc to use private key in Golang

- .travis.yml
- README.rst
Go has the last two versions support policy. As 1.14 was released in Feb 2012, they dropped the 1.12 support. We want to align with their policy for golang driver.
> remove 1.12 support ad add 1.14

- datatype.go
- dsn.go
- dsn_test.go
- errors.go
Handle conflict between specified region (deprecated) and implicit region from dsn account
> Handle deprecated region dsn parameter conflict

- .github/workflows/semgrep.yml
- .semgrep.yml
update semgrep PR check name and update rule pack to include remediation guidance and reference
The semgrep check name is updated to be less generic and also the rule pack was updated to have messages with better remediation info as well as links to internal confluence for remediation
> CASP-865 update semgrep check name and rule pack messages

- chunk_arrow.go
A single chunk can contain multiple fragmented records whilst we were assuming a one-to-one mapping previously.
> SNOW-186535 Fix arrow chunk decoding

- doc.go
SNOW-185829
Remove the preview note from the multi-statement documentation. Multi-statement support will be generally available as of 1.3.8.
> SNOW-185829 Remove the preview note from the multi-statement documentation

- auth.go
- auth_test.go
- authexternalbrowser.go
- authokta.go
- authokta_test.go
- benchmark/jsonresultset/Makefile
- benchmark/largesetresult/Makefile
- connection.go
- connection_test.go
- driver.go
- dsn.go
- gosnowflake.mak
- heartbeat.go
- ocsp.go
- ocsp_test.go
- restful.go
- restful_test.go
- result.go
- retry.go
- rows.go
- rows_test.go
- statement_test.go
Added
- Update chunk download helper function signature to return error and handle error
- Parity in function signatures within restful.go / restful object
- Handle request timeout errors for restful object
- Add and expose the query ID for DMLs as a part of Snowflake result
Not added
- New describeContext function (sets parameter describeOnly) at the statement level. Requires exposing this function by making Snowflake Statement object public as well.
> SNOW-183510 Update context behavior function signatures

- .github/workflows/build-test.yml
- README.rst
Removed Go 1.13 tests in line with dropping support for Go 1.13.
> SNOW-183506 Drop support of Go 1.13

- authexternalbrowser.go
An error is introduced when attempting to connect using an external browser cmd for authentication. The response returned by the browser does not always contain a token and therefore throw a "response is malformed" error. This fixes this issue by putting the listener in a goroutine and nesting the original process inside it and use a channel to return the value of the token.
> SNOW-208207 Fix External Browser Authentication Token Error

- connector.go
- connector_test.go
- doc.go
- driver.go
- driver_test.go
- dsn.go
SNOW-209089
In order to support manual auth token accessor / management, we
need a clean way to intercept HTTP requests and responses and manually
set AUTH header, retry, and reauth.
Add an optional value to the config so that an override Http transport
can be specified. When the Transport is specified, the REST client will
use this transport instead of the default snowflake transport.
Testing
Added unit test to verify that config transport is indeed the one
used by the snowflake restful http client
This is built upon https://github.com/snowflakedb/gosnowflake/pull/343 which allows
opening connection with custom Config
> SNOW-209089 Add HTTP transport override to support future token accessor

- connector.go
- connector_test.go
- doc.go
- driver.go
- driver_test.go
- dsn.go
Description
Add the ability to open a connection using a specific Config struct.
Over time, additional non-string representation config options will be implemented,
so we would like the ability to specify the Config directly vs always stringify into a DSN.
Testing
All existing unit tests hit new code path.
> SNOW-209090 Support opening connection with Config struct

- .github/workflows/build-test.yml
This will add a button for build-test workflow to run it manually . This will be useful for Releng team to run GoLang tests on master or any other branch as part of pre-release of server release is done to ensure it does not break GoLang connector
> SNOW-208979 Add option to trigger Github Action Build/Test manually

- connection.go
- driver.go
- query.go
- restful.go
- result.go
- rows.go
- statement.go
- statement_test.go
This PR allows asynchronous querying by enabling the AsyncExec parameter to be set via the driver, which, when sent to the server, will not block waiting for the entire query to finish.
> SNOW-160505 Async Support

- auth.go
- auth_test.go
- authokta.go
- connection.go
- connection_test.go
- doc.go
- driver_test.go
- restful.go
- restful_test.go
- util.go
- util_test.go
GS rest endpoint requires UUID in the V1 endpoint.
It will return a bad request if the request ID is not UUID.
On HTTP400, the http retry logic still kicks in and end up
causing a hang due to retrying a bad query.
To fix this, I'm proposing the following changes:
1. Make request ID always UUID type, and check against UUID.nil
2. postQueryHelper should not retry on 4xx error, any 4xx error should be bubbled up
Testing
Added new unit test
> SNOW-274063 QueryRowContext hangs on bad request

- connection.go
- restful.go
- statement.go
- statement_test.go
Interface to capture query ID as soon as it's ready using a channel passed through a context.
> SNOW-212952 Emit Query ID

- chunk_downloader.go
- chunk_test.go
- connection.go
- multistatement_test.go
- rows.go
- rows_test.go
Add support for processing multi-column result sets by modifying the RowType per chunk downloader, necessary for multi-statement executions/queries.
> SNOW-257769 Multi Column Result Sets

- auth.go
- auth_test.go
- authokta.go
- authokta_test.go
- connection.go
- connection_test.go
- driver.go
- dsn.go
- heartbeat.go
- restful.go
- restful_test.go
- util.go
- util_test.go
Introduce the concept of a token accessor interface that can be used to
manage the lifecycle of token & master token & session ID.
Currently, token, master token, and session ID are tied directly to `snowflakeRestful`.
Instead, allow a `TokenAccessor` to be defined in the `Config` and let the token accessor
manage setting, and retrieving the token to use when making REST calls.
Added new unit tests and updated existing tests to make sure queries carry
the token from the token accessor, and session renewals set the token back into the accessor.
> SNOW-209082 Introduce TokenAccessor to manage tokens and sessions

- doc.go
SNOW-294398
I noticed that I was inconsistent about using upper-case vs. lower-case for the queryContext function. I *think* it's supposed to be InitCap ("QueryContext"), so that's what I changed it to. If that's wrong, please let me know and I'll re-do the fix.
Thank you.
> SNOW-294398: Change queryContext() to the correct case: QueryContext.

- ocsp.go
- ocsp_test.go
Create ocsp_response_cache.json file if it doesn't exist.
> SNOW-294718 Fix OCSP Error on Init Bug

- heartbeat.go
- restful.go
- restful_test.go
- util.go
- util_test.go
When a request comes back as session expired, we issue a
session renewal and rotate the token in the token accessor.
Multiple requests can hit the same session expired error at
the same time, and trigger multiple renewals of the same stale token.
Use a mutex to synchronize the token renewal, and only issue
one renewal for the stale token.
Testing
New tests with multiple goroutines added to verify concurrency.
> SNOW-291628 Synchronize the session renewal when token expires

- connection.go
- connection_test.go
- dsn.go
Added a control flow to keep client session alive if parameter enabled.
> SNOW-209092 Skip Session Close

- doc.go
SNOW-166520: Add documentation about support for the Arrow data format, including an expanded data conversion table.
Also fixed a few other minor things that I saw.
> Mgilkey snow166520 golang and arrow 2021 05

- auth.go
- auth_test.go
- put_get_test.go
- restful.go
- restful_test.go
- util.go
- util_test.go
Change session ID to int64 type for 32-bit systems
> SNOW-354479 Change Session ID to int64

- bind_uploader.go
- bindings_test.go
- converter.go
- converter_test.go
- driver_test.go
- prepared_statement_test.go
Extension of array binds. Adding support for timestamp, time, date and byte array bindings.
> SNOW-292862 Additional Array Bind Types

- restful.go
- restful_test.go
- util.go
Enable retry for cancellation queries. Default value is 5
> SNOW-342743 Cancellation Retry

- doc.go
Our Snowflake standard is to write "a SQL" ("a sequel") rather than "an SQL" ("an ess-queue-ell"), but I often forget, so I had to fix it.
Also, S3 storage is properly named "Amazon S3" rather than "AWS S3", so I fixed that, too.
> SNOW-180452: Change 'an SQL' to 'a SQL' to match our standards.

- doc.go
Removed the line saying that PUT is not supported by the Golang driver.
> SNOW-365333: Removed statement that PUT is not supported.

- bindings_test.go
- chunk_arrow.go
- chunk_downloader.go
- connection_test.go
- converter.go
- converter_test.go
- doc.go
- driver.go
- driver_test.go
- rows_test.go
- util.go
Enable client side flag that enables higher precision for Arrow.
> SNOW-370765 Arrow High Precision Flag

- chunk_test.go
- ctx_test.go
- doc.go
- driver_test.go
- ocsp.go
- ocsp_test.go
- telemetry.go
Demoted OCSP cache errors to warnings to declutter logs.
> SNOW-302103 Disable OCSP Cache Errors in Logs

- .github/workflows/build-test.yml
Drop support for Go 1.14 and 1.15, in line with Golang's official support. Adding support for Go 1.17.
> SNOW-420791 Drop Support for Go 1.14, 1.15; Add Support for 1.17

- connection_util.go
- file_transfer_agent.go
- put_get_test.go
- query.go
- s3_util_test.go
- storage_client.go
Make overwrite = true the default for PUT operations unless otherwise specified.
> SNOW-444264 Make PUT overwrite default

- async.go
- errors.go
- file_transfer_agent.go
- multistatement.go
Add error checking for missing result IDs
> SNOW-534077 Multi-Statement Missing Result IDs

- bind_uploader.go
Prior to this, the buffer maximum could be exceeded if a
column's byte count was >8
I'm unable to run the tests myself, so I'm not sure if this
breaks any of them. It does totally seem to resolve the
issue I've been having in trying to upload large batches
though!
> bind_uploader: don't allow more than 10M in upload buffer

- .github/workflows/jira_issue.yml
SNOW-623405
Jira area numbers seem to have changed, in this PR I update the GitHub Action to use the new correct Area id.
> SNOW-623405 Update jira_issue.yml

- authexternalbrowser.go
- authexternalbrowser_test.go
Simba incident 00388511
When the SAML token encryption is enabled in the identity provider, the driver fails authenticating with an external browser because part of the token was trimmed.
> Fixes external browser failed with encrypted SAML assertions

- statement_test.go
Follow up on #590.
TestCallStatement in statement_test.go will be disabled until server supports the parameter USE_STATEMENT_TYPE_CALL_FOR_STORED_PROC_CALLS
> Disable the test for new statement type CALL

- bind_uploader.go
- bindings_test.go
- converter.go
- converter_test.go
- doc.go
SNOW-590709 (Simba incident 00383422)
The driver currently supports inserting NULL one by one but not in batch (i.e. array binding). Also, NULL cannot be inserted in arrays like []int and []string, so user will need to use the interface slice []interface{}.
This PR has added support for using interface slice []interface{} in array binding so that NULL can be inserted in batch.
Data types supported: INTEGER, FLOAT, STRING, BOOLEAN, BINARY
Not supported: DATE, TIME, TIMESTAMP_LTZ , TIMESTAMP_NTZ , TIMESTAMP_TZ
> SNOW-590709 Support for using interface slice []interface{} in array binding

- bind_uploader.go
- bindings_test.go
- converter.go
- converter_test.go
- doc.go
SNOW-590709 (Simba incident 00383422)
Part 2 for #629 to support the DATE, TIME, TIMESTAMP_LTZ , TIMESTAMP_NTZ , TIMESTAMP_TZ data types to be used in slice []interface{} for array binding.
> SNOW-590709 Support time.Time types in slice []interface{} for array binding

- bind_uploader.go
- encrypt_util.go
- encrypt_util_test.go
Fix the "Failed to decrypt. Check file key and master key" error that occurs when uploading a file which the size is a multiple of 65536 bytes. Missing padding bytes at the end of the file is the root cause of the issue.
Removed the temporary workaround in #583.
> SNOW-559914 Fix multipart binding upload failure due to missing padding

- doc.go
- driver.go
- dsn.go
Add a connection property 'Tracing' to enable logging via connection string or DSN.
> Add parameter to enable logging in connection string / DSN

- connection_test.go
There was a fix for scan bytes deployed on the snowflake server around end of September and caused the test TestGetQueryStatus to fail. This PR updates the expected result in the test.
> Updated expected result after scan bytes fix on the server side

- chunk_downloader.go
- chunk_test.go
- rows.go
Salesforce ticket 00396666
The GetArrowBatches() API was implemented to access data in arrow.Record format directly from queries (#544).
However, the API is not public so it's not usable by customers. It is also not a blocking call which results in panic in async mode.
This PR adds the public interface SnowflakeRows and exposes the functions GetQueryID(), GetStatus() and GetArrowBatches(). This matches the functions that are exposed in SnowflakeResult. GetArrowBatches() is also changed to a blocking call to ensure the arrow batches are ready before fetching it. Customer has verified the changes in this branch.
> Change GetArrowBatches() in snowflakeRows to be public and blocking call

- bindings_test.go
- converter.go
Take change from #655 to remove high precision check on non-fixed types i.e. FLOAT/REAL/DOUBLE.
For fixed types i.e. NUMBER/DECIMAL, use the column metadata scale when formatting: fmt.Sprintf("%.*f", srcColumnMeta.Scale, f)
Fixes #578
> Change string format for float and numeric when converting arrow types

- .github/workflows/build-test.yml
- README.md
- auth.go
- authexternalbrowser.go
- authokta.go
- azure_storage_client.go
- chunk_downloader.go
- cmd/oauth/oauth.go
- cmd/showparam/showparam.go
- connection_test.go
- doc.go
- encrypt_util.go
- encrypt_util_test.go
- file_transfer_agent.go
- file_util.go
- go.mod
- go.sum
- heartbeat.go
- local_storage_client.go
- log.go
- ocsp.go
- ocsp_test.go
- priv_key_test.go
- put_get_test.go
- put_get_user_stage_test.go
- put_get_with_aws_test.go
- restful.go
- retry.go
Drop support for go 1.17 and add support for go 1.19
io/util package is deprecated with 1.16. This also replaces usages with either os or io.
> Drop support for go 1.17 and upgrade to go 1.19

- file_transfer_agent.go
- file_transfer_agent_test.go
Simba Salesforce ticket number 00406729.
Description provided by Snowflake Support:
When we need to upload a file to an internal stage using the PUT command it fails when GetBucketAccelerateConfiguration returns 405.
It happens when the driver tries to use the S3 acceleration service on the accounts where the S3 Acceleration is disabled on the buckets. 
Observed behavior:
The driver fails with: ERRO[0000]connection.go:318 gosnowflake.(*snowflakeConn).queryContextInternal error: operation error S3: GetBucketAccelerateConfiguration, https response error StatusCode:
The file is not uploaded
In Snowflake job history the PUT query appears successful
Expected behavior:
The 405 error appears in the log
The file is uploaded
In Snowflake job history the PUT query appears successful
(This is how it …
> Ignore 405 error when S3 Acceleration is disabled on the S3 bucket

- go.mod
- go.sum
- vendor/golang.org/x/sys/plan9/syscall.go
- vendor/golang.org/x/sys/plan9/syscall_plan9.go
- vendor/golang.org/x/sys/unix/mkerrors.sh
- vendor/golang.org/x/sys/unix/zerrors_linux.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
- vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
- vendor/golang.org/x/sys/unix/ztypes_linux.go
- vendor/golang.org/x/sys/windows/setupapi_windows.go
- vendor/golang.org/x/sys/windows/syscall_windows.go
- vendor/golang.org/x/sys/windows/types_windows.go
- vendor/modules.txt
Caused by PR #661. Vendor\Modules.txt has some unresolved conflicts.
> Fix modules.txt conflicts

- encrypt_util.go
- errors.go
- file_transfer_agent.go
- file_transfer_agent_test.go
1. SNOW-636725: panic: crypto/cipher: input not full blocks (Issue #632): Add padding when the source being decrypted is not divisible by block size (16).
3. SNOW-636720: Panic due to slice bounds out of range in paddingTrim (Issue #631): Add check on unpadding to make sure the length is not 0 or too big. Return an error if the padding is invalid.
4. SNOW-636717: Panic inside `snowflakeFileTransferAgent.parseCommand` due to nil pointer dereference (Issue #630): check for error first to avoid nil pointer reference.
The customer has confirmed the fixes on their end.
> Fix panic issues in file downloading

- ci/build.bat
- gosnowflake.mak
The latest version of static check (0.4) requires Go 1.19 or 1.20. Currently we support 1.18 and 1.19.
This is to force the driver to use 0.3 instead of latest until we support 1.20.
> Set version of static check to 0.3

- .github/workflows/build-test.yml
- README.md
- ci/build.bat
- driver_ocsp_test.go
- driver_test.go
- file_compression_type.go
- go.mod
- gosnowflake.mak
Go 1.20 has been released: https://go.dev/doc/devel/release#go1.20
Drop Go version 1.18 and add support for Go 1.20.
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/200
> Drop Go 1.18 and add Go 1.20

- authokta.go
- retry.go
- retry_test.go
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/179
> Add support for new OKTA OIE and retry 429 error code

- go.mod
- go.sum
- vendor/modules.txt
Replace golang.org/x/text with v0.8.0 and gopkg.in/yaml.v3 with v3.0.1
Fix:
#673 #623 #612 #608 #605
> Replace golang.org/x/text and gopkg.in/yaml.v3 with latest versions

- url_util.go
- util_test.go
Added URL Validator to ensure that the SSO URL being used in external browser is valid. Also added URL Encoder to encode base64 strings to url safe format.
> SNOW-761744 Added URL Validator and URL Encoder

- bind_uploader.go
- bindings_test.go
- converter.go
- converter_test.go
Issue: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/246
Starting with gosnowflake 1.6.13, the use of a pointer *time.Time type in user-defined structures used to perform updates/inserts has silently stopped working, and nil value is used instead of the value it points to.
This PR fixes the regression introduced by PR #642. All array binding insertion using []interface{} will now be wrapped in the  interfaceArrayBinding struct, instead of assuming them as the reflect.Slice and reflect.Struct types.
```
type interfaceArrayBinding struct {
hasTimezone       bool
tzType            timezoneType
timezoneTypeArray interface{}
}
```
> SNOW-755844: Pointer datatype *time.Time returns <nil> value

- connection.go
- connection_test.go
Issue 289: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/289
The driver panics when it tries to cast a generic error to `SnowflakeError` and access the `SnowflakeError.Number` field:
This PR fixes the interface conversion panic by checking if the casting succeeds before accessing the Number field.
> SNOW-559970 Fixed interface conversion error when error is not SnowflakeError type

- chunk_downloader.go
Issue 300: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/300
The data chunk at index 0 is not cleaned up until the end when reset() is called in [rows.go](https://github.com/snowflakedb/gosnowflake/blob/master/rows.go#L174) and consumes memory.
This PR cleans it up by freeing the chunk before reading the next chunk.
> SNOW-747896: Clean up the first chunk of data that has been previously used

- converter.go
- converter_test.go
Fixes #678 
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/310
The epoch nanosecond value for large and small timestamps (i.e. year 6000 / year 9000) cause an overflow with go's int64 type. This PR is to use big int instead of int64 for coverting the timestamp to string.
> SNOW-684693 Fix small/large date/time overflow 

- connection.go
- transaction.go
- transaction_test.go
Fixes #796 
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/378
Commit() and Rollback() are currently not using the same context set in BeginTx(), they are using the context stored in the parent snowflakeConn object. If a connection context has a short deadline, it can result in commit() or rollback() not being called after a transaction due to the deadline exceeded. This is causing locks in customers environment when subsequent sessions hang and fail.
> SNOW-823072: Use the context object supplied by BeginTx instead of from the parent connection

- cmd/externalbrowser/externalbrowser.go
- cmd/keepalive/keepalive.go
- cmd/keypair/keypair.go
- cmd/mfa/mfa.go
- cmd/noconnpool/noconnpool.go
- cmd/selectmany/selectmany.go
- cmd/showparam/showparam.go
> Make port/portStr variables in cmd more consistent

- transaction.go
Common code was extracted to separate function. In addition to that, an enum representation of transaction command was added to disallow any string being passed as a transaction command.
> SNOW-828186 Remove code duplication in transaction.go

- async.go
- async_test.go
For #768 and #795 
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/323
If a statement is executed and the execution is completed in 45 seconds, the server returns the result. If the statement execution takes longer to complete, the statement handle is returned. 
In the current driver implementation, when making a get request to the `/queries/<query-id>/result` endpoint, the response will be processed even if the server returns the queryInProgressAsyncCode (333334). Since it doesn't check the response code for in progress queries, it will be marked as complete even though the query hasn't finished and the result was not returned. 
This change is to retry the request to the /result endpoint if the query is still in progress so that results are retrieved for …
> SNOW-782588: Retry result request for async query if still in progress

- file_transfer_agent.go
- file_transfer_agent_test.go
Fixed driver panicking when the temp filesystem is readonly.
> SNOW-723750: Panic with readonly file system

- .github/workflows/cla_bot.yml
CLA Assistant check has been failing for release branches. The failure is due the jenkins user used to create the branch and do the commit is not in the allowed list in that check. 
The fix is to add it.
> SNOW-845733 - Add Jenkins user to allow list for CLA Assistant check

- connection.go
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/491
An intermittent issue was reported where if a query failed while executing queries simultaneously, the wrong error message could be shown in the log.
The root cause is that during processing of the query response from the server inside the exec() function, there is a function populateErrorFields(). If two or more query responses are returned simultaneously and enter this function around the same time, it can cause a race condition where the error data is updated incorrectly. I am able to reproduce this about ~60% of the time without this change.
> SNOW-848019: Add mutex lock to prevent race condition in populateErrorFields()

- auth.go
- authexternalbrowser.go
- authexternalbrowser_test.go
- dsn.go
Adds the timeout for the external browser authentication. Defaults to 120s.
> SNOW-847338: Add timeout for authentication in external browser

- dsn_test.go
Add missing parameter ExternalBrowserTimeout check in tests.
> SNOW-856850: Add missing parameter check in tests

- dsn.go
- dsn_test.go
Fixes https://github.com/snowflakedb/gosnowflake/issues/843
Snowflake required username and password in most auth types, even if they don't really needed. Fix enables username and password checking only if they are really required.
> SNOW-857829 Fix username and password requiredness

- connection.go
Some queries will not return Arrow data even when requested with format == arrow, such as "SHOW WAREHOUSES". This ended up causing an [issue](https://github.com/apache/arrow-adbc/issues/863) in ADBC when it happened. In order to address this scenario, we need to expose the raw json data through the ArrowStreamLoader in addition to the batches.
> fix(arrow): handle non-arrow result sets

- bind_uploader.go
- bindings_test.go
Fixes https://snowflakecomputing.atlassian.net/browse/SNOW-645253 / https://github.com/snowflakedb/gosnowflake/issues/644
Binding does not work for two cases (date/time) - but it doesn't work for any times of binding, not just for named parameters. Need to investigate it further, will provide solution in another PR.
> SNOW-645253 Handle binding named parameters

- arrow_test.go
- async_test.go
- bindings_test.go
- connection_test.go
- driver_test.go
- file_transfer_agent_test.go
- multistatement_test.go
- priv_key_test.go
- put_get_test.go
- put_get_user_stage_test.go
- put_get_with_aws_test.go
- rows_test.go
- statement_test.go
- transaction_test.go
All tests opened new connections, even if they could reuse a connection from the pool. Migrating to the pool decreased tests time around 15%.
> SNOW-859548 Reuse connection in tests

- bindings_test.go
- driver_test.go
Each test did a round trip or even two to drop tables, which were not created in most tests. Additionally, all test tables are dropped on the end of the suite, when the whole schema is dropped.
> SNOW-859548 Replace test table in each test

- connection_test.go
- dsn_test.go
- log_test.go
Increase log.go coverage to 82.7% and cover missing critical areas in dsn.go and connection.go.
> SNOW-540086: cover critical areas test code coverage for logger, dsn and connection

- .github/workflows/build-test.yml
- Do not cancel other matrix builds when one fails
- Cancel build when new code in branch appears
> SNOW-880396: Do not cancel other matrix builds when one fails

- bindings_test.go
- connection_test.go
- converter_test.go
Increase code coverage for converter.go to 92.0% to cover critical areas missed.
> SNOW-540086: Increase code coverage on converter.go

- azure_storage_client.go
- doc.go
- encrypt_util.go
- encrypt_util_test.go
- file_transfer_agent_test.go
- file_util.go
- gcs_storage_client.go
- local_storage_client.go
- local_storage_client_test.go
- ocsp.go
- ocsp_test.go
- put_get_test.go
- put_get_user_stage_test.go
- put_get_with_aws_test.go
- s3_storage_client.go
- secure_storage_manager_test.go
> Test pr 865

- chunk_downloader.go
Pass context to Arrow `Fetch` function to enable specific contexts like cancellations etc.
> SNOW-880442: Add pass context to arrow fetch function

- file_transfer_agent.go
When executing a command the fileTransferAgent checks the srcFileSize and assigns it to either large or small file metadata. Large file metadata is uploaded/downloaded sequentially while small file metadata is uploaded/downloaded in parallel.
However, the srcFileSize for downloading is always 0, since we don't yet know the file size in the stage. So when it hits [this block](https://github.com/snowflakedb/gosnowflake/blob/master/file_transfer_agent.go#L169), it will always be added to small file metadata and then downloaded in parallel.
This PR is to remove the unused function.
> SNOW-540086 Code coverage: Refactor unused function downloadFilesSequentially()

- driver.go
- driver_test.go
- dsn.go
- dsn_test.go
- errors.go
- file_transfer_agent.go
- file_transfer_agent_test.go
- put_get_test.go
Introduces configuring temp dir used for encryption and compression. The change was needed as in some container environments temporary directory is readonly.
> SNOW-845282: Allow configuring tmpdir in DSN

- location.go
- location_test.go
- rows.go
- rows_test.go
Initialize location once per query, instead of creating it for each row and column.
> SNOW-857660: Init rows location once

- azure_storage_client_test.go
- bindings_test.go
- converter_test.go
- datatype_test.go
- driver_test.go
- dsn_test.go
- encrypt_util_test.go
- file_transfer_agent_test.go
- file_util_test.go
- gcs_storage_client_test.go
- location_test.go
- multistatement_test.go
- ocsp_test.go
- put_get_test.go
- s3_storage_client_test.go
- secure_storage_manager_test.go
- util_test.go
Added `t.Run` in tests which create subtests. Before first for any test case causes test failure. Now, all test cases are run independently and do not depend on the previous instances. Also, Go and IDE recognise instances as separated tests.
> SNOW-859547: Refactor tests to create a new test for each test case

- htap.go
- htap_test.go
Provided query context structs and tests for serialisation and deserialisation.
> SNOW-895534: Add HTAP query context struct

- connection.go
- multistatement.go
- rows_test.go
QueryID was persisted in snowflakeConn and read by some functions. It could cause race conditions if the same connection is reused among threads. Now, the queryId is read from the responses.
> SNOW-726742 Remove queryID from snowflakeConn

- connection.go
- connection_test.go
- dsn.go
- dsn_test.go
- errors.go
- version.go
Refactored global error objects to functions that create new instances to avoid thread mutability issues.
> SNOW-848019 Change global error objects to instantiated by function

- doc.go
- statement.go
- statement_test.go
Implement GetQueryId on statements
> SNOW-726742: Implement GetQueryId for statements

- htap.go
- htap_test.go
Introduced algorithm of prioritising entries in query context cache.
> SNOW-895535: Prioritise entries in query context cache

- connection.go
- doc.go
- dsn.go
- dsn_test.go
- htap.go
- htap_test.go
- query.go
Provided parameter to disable query context cache
> SNOW-911181: Add parameter to disable query context cache

- connection.go
- driver_test.go
- htap.go
- htap_test.go
- query.go
Query contexts are now sent to snowflake backend.
> SNOW-895537: Send query context with request

- arrow_test.go
- connection.go
- connection_util.go
- multistatement_test.go
Provided way of handling new multistatement query type.
> SNOW-857631 Handle multistatement query type

- aaa_test.go
- connection.go
- htap_test.go
Enables htap optimizations - not sending db/schema/warehouse/session parameters.
> SNOW-898296: Enable HTAP optimisations in tests

- arrow_chunk.go
- chunk_downloader.go
- cmd/arrow/batches/arrow_batches.go
- connection.go
- converter.go
- converter_test.go
- datatype.go
- errors.go
- rows.go
- util.go
Add WithOriginalTimestamp context switch.
> SNOW-911238: Add WithOriginalTimestamp context switch 

- client_configuration.go
- client_configuration_test.go
- go.mod
> SNOW-856228 easy logging parser

- encrypt_util.go
- encrypt_util_test.go
- put_get_test.go
- put_get_user_stage_test.go
- put_get_with_aws_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
if err != nil {
t.Error(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
> test: use `T.TempDir` to create temporary test directory

- assert_test.go
- client_configuration_test.go
> SNOW-856228 better assertions in easy logging

- .github/workflows/build-test.yml
- connection_test.go
This test failed randomly when concurrent threads were run. If no row was read, the connection was returned to the pool too fast, before chunk decoding (in another thread) was finished. Currently, as we read from the rows, this object is not returned to the pool too early.
> Fix TestConcurrentReadOnParams cleaning up the connection too early

- async_test.go
- connection.go
If the context has been set to Async Mode, the driver will attempt to
inspect the result type. If the result type has not been set, the driver
will panic when returning the [partial] result.
We ran into this issue when pinging a connection to test for aliveness when the context had `WithAsyncMode` applied. While async mode doesn't make a lot of sense for pings, in this case the same context is used to ping before executing a query.
Happy to write a test, just wasn't clear to me where Ping tests would live.
> Set the result type before calling exec from Ping

- cmd/async/async.go
Before this change async mode used `sql.DB` and invoking query caused synchronous logging in.
> SNOW-949224 Introduce conn in async example

- auth.go
- chunk_downloader.go
- connection.go
- dsn.go
- dsn_test.go
- ocsp.go
- restful.go
- restful_test.go
- retry.go
- retry_test.go
Added MaxRetryCount as configurable parameter. It specifies how many times requests can be retried.
> SNOW-878073 Add MaxRetryCount as configurable parameter

- client_configuration.go
- client_configuration_test.go
Prevent to fail if client config file could not be found because of an unexpected error during the phase of searching in predefined directory.
> SNOW-856228 easy logging - not fail on directory serch error

- chunk_test.go
- connection.go
Modify snowflakeConn.QueryArrowStream to take the "describe only" flag on the context into account.
References #954
> Support DescribeOnly for QueryArrowStream

- connection.go
- doc.go
- easy_logging.go
- easy_logging_test.go
> SNOW-856228 Disable easy logging

- put_get_test.go
Fix PUT overwrite test to align GCP to remaining clouds. This was caused by snowflake backend change for GCP downscoped tokens.
> SNOW-949229 Adjust TestPutOverwrite to GCP downscoped tokens

- authexternalbrowser.go
- authexternalbrowser_test.go
- dsn.go
- dsn_test.go
- gcs_storage_client.go
- gcs_storage_client_test.go
- statement.go
- statement_test.go
Use a multi-valued interface conversion instead of a single-value form to avoid runtime panic.
Fix for #940
> fix: remove unsafe interface conversion

- statement.go
- statement_test.go
Remember queryId for failed queries.
> SNOW-968719: Remember queryId for failed queries

- ocsp.go
> SNOW-961482 Change OCSP response cache key to base64 encoded certID

- s3_storage_client.go
- s3_storage_client_test.go
Upgraded AWS SDK library. Upgrade was needed as AWS client changed incompatibly.
Kudos for @kenshaw for suggesting the backward compatible solution!
> SNOW-974548 Upgrade AWS SDK

- htap_test.go
Skip HTAP test until AWS issue is sorted.
> SNOW-982511: Skip test until AWS issue is sorted

- monitoring.go
- restful.go
- retry.go
- retry_test.go
Fixed retry algorithm. Before, only whitelisted endpoints were retried. Now it retries all endpoints. Also, there is a separate backoff logic for authentication endpoints.
> SNOW-981533 Separate retry strategy for auth endpoints and the remaining ones

- htap_test.go
> SNOW-982511: Enable HTAP test

- retry_test.go
Fixes flaky test introduced when retry strategy changed.
> SNOW-981533 Fix flaky test of retries

- .github/workflows/build-test.yml
Use latest macos image and sync time before the tests.
> SNOW-969837: Use macos-latest and sync clock

- connection.go
- doc.go
- statement_test.go
- util.go
1. Add new `WithQueryTag` method to allow clients to pass the `QUERY_TAG` parameter to a query via the context
2. Add test to verify that we're setting the tag correctly
> allow clients to set QUERY_TAG parameter via context

- arrow_chunk.go
- chunk_downloader.go
- chunk_downloader_test.go
When error occurred when parsing first arrow batch, the error was just swallowed and empty struct was returned. This caused that when the struct was used, caused panic on nil field access.
> SNOW-985356 Do not start chunk downloader when first batch causes error

- retry.go
This change excludes statuses 400 & 405 from retry strategy as these should not be retried.
> SNOW-991467 Remove 400 & 405 statuses from retry

- assert_test.go
- chunk_downloader.go
- chunk_downloader_test.go
SNOW-988793 When arrow batches mode is used and the query returns no rows - we shouldn't create arrow reader at all.
> SNOW-988793 Do not read arrow chunk when it is empty for arrow batches

- assert_test.go
- s3_storage_client.go
- s3_storage_client_test.go
> SNOW-994698 cover corner cases where an unexpected non APIerror occurs during HeadObject

- ci/scripts/test_component.sh
- ci/test.bat
> Restore test timeout to 30m

- azure_storage_client.go
- gcs_storage_client.go
- s3_storage_client.go
Use the same transport configuration for all stages.
> SNOW-996678 Use snowflakeTransport for all clouds

- async.go
- async_test.go
- cmd/fetchresultbyid/.gitignore
- cmd/fetchresultbyid/Makefile
- cmd/fetchresultbyid/fetchresultbyid.go
- doc.go
- monitoring.go
issue: [#705](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/705)
using:
```
ctx = gosnowflake.WithFetchResultByID(ctx, queryId)
rows, err := s.db.QueryContext(ctx, "")
```
will return no error and no result after about 45 seconds.
This PR applies the same change as [PR #824](https://github.com/snowflakedb/gosnowflake/pull/824) to check for the status `queryInProgressAsyncCode` in `rowsForRunningQuery` in `monitoring.go`
> SNOW-942595: Retry the fetch result request for response code queryInProgressAsyncCode when using WithFetchResultByID

- auth.go
- auth_test.go
issue: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/655
The native Okta Authentication fails in retry due to the same token is used in an sso/saml retry.
This PR fixes the retry logic by generating a new token each time it retries.
> SNOW-916951: Retry okta auth with new token

- assert_test.go
- chunk_downloader.go
- chunk_downloader_test.go
[SNOW-1016278](https://snowflakecomputing.atlassian.net/browse/SNOW-1016278) Fixes getting arrow batches when query returns no results at all.
[SNOW-1016278]: https://snowflakecomputing.atlassian.net/browse/SNOW-1016278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-1016278 Fix panic on empty arrow batches

- doc.go
Added docs about the feature introduced in SNOW-911238.
> SNOW-911238 Add doc about WithOriginalTimestamp

- cmd/arrow/batches/arrow_batches.go
- converter.go
- converter_test.go
- doc.go
- util.go
Address https://github.com/snowflakedb/gosnowflake/issues/910 when driver only needs microsecond or millisecond precision. 
In our use case, the connector passes the arrow record from Snowflake to another service for decoding. If we only want microsecond precision, we can avoid the need to port the `arrowSnowflakeTimestampToTime` logic.
it would be best if we don't need to repack Snowflake response from Snowflake internal format to arrow timestamps in driver. I understand that might require your backend work. In the meanwhile we can have the driver change as a short term solution.
> support millisecond and microsecond for arrow batch timestamp

- doc.go
Fixed a typo. Exmaple to example 2x in doc.go.
- [✅] Code compiles correctly
- [✅] Run ``make fmt`` to fix inconsistent formats
- [✅] Run ``make lint`` to get lint errors and fix all of them
- [✅] Created tests which fail without the change (if possible)
- [✅] All tests passing
- [✅] Extended the README / documentation, if necessary
> DOCS: Fix exmaple -> example (2x)

- client_configuration.go
- client_configuration_test.go
- easy_logging_test.go
Fix application directory which is used to get the config file.
> SNOW-999076: Fix application directory

- version.go
> Updated gosnowflake version to 1.8.0

- README.md
- driver.go
- util.go
SNOW-903604 Zombie dbus processes generated by one of our dependencies github.com/99designs/keyring
After long consideration and discussion how we want to address the issue we decided to go with only documenting for now, which is what i tried to do here, alongside with trying to detect if the OS is susceptible for the issue (not all Linux are)
If so, log a warning of the issue + workaround which is the same as documented in the README now.
Of course this is by no means a solution - long term solution will be to possibly replace the current keyring implementation.
> SNOW-903604 Zombie dbus processes generated by one of our dependencies github.com/99designs/keyring

- assert_test.go
- doc.go
- retry.go
- retry_test.go
issue 804: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/804
This PR fixes the retry backoff period for query requests. 
- changed the base wait time from 5s to 1s
- changed the max wait time from 160s 16s
- The implementation now matches the JDBC driver's [decorrelated jitter](https://github.com/snowflakedb/snowflake-jdbc/blob/master/src/main/java/net/snowflake/client/util/DecorrelatedJitterBackoff.java#L19C15-L19C28)
> SNOW-991467: Fix retry backoff period for non-auth requests

- converter.go
- converter_test.go
- doc.go
- util.go
For historical reasons, snowflake used to allow users to upload invalid utf-8 characters. This caused arrow record to contain invalid utf-8 characters in arrow string columns. 
However by definition arrow.String column should contain utf-8 characters only, see https://arrow.apache.org/docs/cpp/api/datatype.html, 
https://github.com/apache/arrow/blob/a03d957b5b8d0425f9d5b6c98b6ee1efa56a1248/go/arrow/datatype.go#L73-L74
This could cause other upstream services that consume the bad arrow record to break, e.g Rust arrow lib force some basic validation, and this bad arrow record will fail the validation. 
This change introduce `enableArrowBatchesUtf8Validation`, when enabled, will iterate all values of string columns and replace any invalid character.
> add enableArrowBatchesUtf8Validation to replace invalid utf8 chars in arrow batch

- chunk_downloader.go
When first arrow batch (returned with query-request response) is empty, download of the remaining chunks does not start at all. This PR fixes this situation.
> SNOW-1222159 Download arrow batches even if first one is empty

- datetime.go
- datetime_test.go
Provided converter from snowflake date time formats to golang formats
> SNOW-1256926 Add converter from snowflake date/time format to go

- arrow_test.go
- assert_test.go
- converter.go
Currently, if you run the query `select '0.1':: DECIMAL(38, 19) as c` with arrow batching turned on, the result will error with `invalid: integer value 1000000000000000000 not in range: -9007199254740992 to 9007199254740992`. The error is thrown by compute.Divide(), when receiving int64 value for a BigDecimal column.
The fix is to convert int64 array to arrow.Decimal array, and follow a different code path (line 943 - line 955) where compute.Divide() is not involved.
The error originates from arrow library: https://github.com/apache/arrow/issues/36998
> ArrowBatch high precision fails when using compute divide from int64 to bigDecimal

- converter.go
- converter_test.go
- doc.go
- util.go
Snowflake returns BigDecimal natively (from backend to driver)
To preserve BigDecimal values within Arrow batches, set the `enableHigherPrecision` value to true in the context using `WithHigherPrecision“.
This offers two main benefits: it helps avoid precision loss and defers the conversion to upstream services.
Alternatively, without this setting, all non-zero scale numbers will be converted to float64, potentially resulting in loss of precision.
> Allow enableHigherPrecision to be used in arrow batches 

- converter.go
- structured_type.go
- structured_type_test.go
SNOW-1256908 When JSON is being deserialized, by default all numbers are deserialized into into float64 and for int64 precision is lost. This change deserializes to string.
> SNOW-1256908 Handle int64 correctly in structured types

- converter.go
SNOW-1321823 Calculate snowflakeType only once. During structured types implementation a perf bug was introduced - snowflakeType for column was calculated every time for each row. Now it is calculated only once per batch.
> Perf for structured type - snowflakeType calculated only once

- async.go
SNOW-1313927 Do not close channels that are closed by deferring closing.
> SNOW-1313927 Do not close channel twice in async handling

- secure_storage_manager.go
SNOW-1313544 Parallel operations on different roles cause program to crash (race condition on temporal credential cache)
Discovered in a Terraform use-case, where there's a lot of resources handled by the Snowflake Terraform Provider 
* moving locks a bit ahead (delete on map happened before lock)
* write-lock instead of read-lock when reading the credentials
> SNOW-1313544 temporal credential cache map race

- README.md
- auth.go
- authexternalbrowser.go
- authokta.go
- bind_uploader.go
- chunk_downloader.go
- connection.go
- connection_util.go
- converter.go
- driver.go
- errors.go
- file_transfer_agent.go
- log.go
- log_test.go
- multistatement.go
- ocsp.go
- restful.go
- retry.go
- rows.go
- secure_storage_manager.go
This will allow the user to set fields on the logs. This is needed because at the moment, the driver does not tag the requestID, so its extremely difficult to debug issues due to the fact that you cant tell which request a log is associated with. Some examples of useful data we could tag with this method includes: client side requestIDs, server side requestIDs given that `gosnowflake.WithRequestID` is used, and snowflake query ID given that we are are using the result reuse feature `gosnowflake.WithFetchResultByID`.
> Allow caller to set log fields

- .github/workflows/jira_issue.yml
SNOW-1334777: Add permission write for create-jira workflow
> SNOW-1334777: Add permission write for create-jira workflow

- auth.go
- auth_test.go
- go.mod
- go.sum
SNOW-1017575 replace deprecated jwt library with supported one
`github.com/form3tech-oss/jwt-go` is deprecated for a long time now and also archived. 
using `github.com/golang-jwt/jwt/v5` instead
besides the usual build test, change has been manually tested with:
* regionless + locator account notation with unencrypted privatekey
* regionless + locator account notation on privatelink with unencrypted privatekey
> SNOW-1017575 replace deprecated jwt library with supported one

- doc/runbook-update-ca-certs.md
- Serial number for instruction to `save file and submit PR`
should be 6, instead of 5.
- Added new line before 6th instruction to improve formatting.
Previously 6th instruction didn't appear on a newline.
> doc: fixed minor typo in runbook-update-ca-certs.md

- connection.go
- log.go
- log_test.go
issue: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/936
SNOW-1260011: Driver exposes password in the logs
The logger will now masked all secrets in the logs.
> SNOW-1260011: mask password in the logs

- converter.go
- structured_type_read_test.go
If we get a snowflake object type, but we haven't set the flag `ENABLE_STRUCTURED_TYPES_IN_CLIENT_RESPONSE`, the code will panic because we are only setting the record on the batch if the snowflake type matches the expected arrow type. This will add support for the underlying type to be either structured or string for snowflake objectType, and if its neither, we will return an error with the underlying type rather than panic so we can fix it
- `TestStructuredTypeInArrowBatchesWithoutEnablingStructureTypes`: check that we can have an object type without setting structured types flag
- `TestNullObject`: ensure that we can have a null object. (This is what was failing in my test suite; ultimately this isn't the actual trigger of the panic, but its still good to test because it could be one …
> [bug fix] objectType should work w/ or wo/ ENABLE_STRUCTURED_TYPES_IN_CLIENT_RESPONSE 

- ocsp.go
SNOW-1335581 Exposed config values for retrying OCSP requests. Decreased default values.
> SNOW-1335581 Decrease number of retires for OCSP

- auth.go
- auth_test.go
- dsn.go
- dsn_test.go
Attempt to fix the issue caused by certain applications putting
* regioned (e.g. myaccount.eu-central-1)
* privatelink (e.g. myorg-myaccount.privatelink)
values in the `Account` field of the configuration, which could result in unsuccessful keypair authentication, as this value was relayed into the JWT unchanged and led to an invalid JWT
The change has been also manually tested by actually generating JWT and actually logging into live Snowflake account, whose names conform the pattern seen in the newly added part in auth_test.go
> SNOW-1432112 verify / sanitize account name before creating JWT

- doc.go
- structured_type.go
- structured_type_read_test.go
SNOW-1416000 Simplified structured objects reading using `ScanTo` function.
> SNOW-1416000 Simplify structured objects reading

- auth.go
- auth_test.go
- doc.go
SNOW-1503458 Added possibility to specify passcode while using MFA token caching
> SNOW-1503458 Allow using passcode with MFA token caching enabled

- driver_ocsp_test.go
badssl.com times out every now and then. We don't want to fail our builds because external service is timing out.
> Fix ocsp test failing on timeout

- driver_test.go
- put_get_test.go
SNOW-116310 Adjusted BINARY col size for select statement used in tests, to match assertions.
> SNOW-116310: Adjust BINARY col size to match assertions

- README.md
- driver.go
- util.go
Revert #1058 except the doc changes
* Short term 'fix' to avoid unnecessary messages due to some apparent false positives
* Long term fix on separate ticket
> Revert #1058 except the doc changes

- doc.go
Added documentation of arrow batches
> Arrow batches documentation

- connection.go
- connector_test.go
SNOW-1563083 Avoid persisting query context in `snowflakeConn`, using it only for dialing purposes as described in [docs](https://pkg.go.dev/database/sql/driver#Connector).
Fixes: #1186
> SNOW-1563083: snowflakeConn creates/manages its own context

- converter.go
- converter_test.go
SNOW-1633839
Fix the following panic. It is illegal to call `IsNil()` on arrays, it's only legal on slices, but we were hitting this code path for both arrays and slices.
```
panic: reflect: call of reflect.Value.IsNil on array Value
goroutine 101 [running]:
reflect.Value.IsNil(...)
/usr/local/go/src/reflect/value.go:1574
github.com/snowflakedb/gosnowflake.arrayToString({0x36b3920, 0xc00413d790}, 0x6, 0xc0014ab7d0)
/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.11.0/converter.go:276 +0x14d7
github.com/snowflakedb/gosnowflake.valueToString({0x36b3920, 0xc00413d790}, 0x6, 0xc0014ab7d0)
/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.11.0/converter.go:264 +0x425
github.com/snowflakedb/gosnowflake.getBindValues({0xc004188000, 0x4a6, 0x10?}, 0xc0014ab7d0) …
```
> SNOW-1633839: Fix error in arrayToString calls

- azure_storage_client.go
- connection_util.go
- doc.go
- file_transfer_agent.go
- gcs_storage_client.go
- put_get_test.go
- s3_storage_client.go
- storage_client.go
SNOW-1660331 // https://github.com/snowflakedb/gosnowflake/issues/1207
attempt to fix
```
unknown field getFileToStream in struct literal of type gosnowflake.SnowflakeFileTransferOptions
```
which happens when trying to download a file into an in-memory stream (rather than a file) per docs:
```go
ctx := WithFileTransferOptions(context.Background(), &SnowflakeFileTransferOptions{getFileToStream: true})
ctx = WithFileGetStream(ctx, &streamBuf)
```
`getFileToStream` being unexported, it is not really accessible from outside of the module.
> SNOW-1660331 export SnowflakeFileTransferOptions.GetFileToStream

- file_transfer_agent.go
- file_transfer_agent_test.go
Ignore and log all errors thrown while getting accelerate configuration from bucket.
> [SNOW-1671768] Ignore max retries error when getting acelerate config

- go.mod
- go.sum
To address https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSIRUPSENLOGRUS-5564391
Affecting github.com/sirupsen/logrus package, versions <1.8.3 >=1.9.0 <1.9.1
Bumping latest logrus version of 1.9.3
> SNOW-1727930 bumping logrus to 1.9.3

- driver_test.go
teamwork issue 1090: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/1090
The test `TestBogusUserPasswordParameters` was removed in PR [#1194](https://github.com/snowflakedb/gosnowflake/pull/1194) due to server changes. This PR added the test back but with different expected error.
> SNOW-1639914: add bogus user password test

- cmd/filestransfer/filestransfer.go
NO-SNOW Fixed filestransfer example - incorrect destination file path.
> NO-SNOW fix filestransfer example

- connection_configuration_test.go
NO-SNOW Fixed letter case in some tests, which was not invoked at all.
> NO-SNOW Enable client configuration tests

- driver_test.go
NO-SNOW Fixes `TestCancelQuery`, which was failing when query finishes too quickly.
> NO-SNOW Fix TestCancelQuery

- auth.go
- authokta.go
- heartbeat.go
- monitoring.go
- restful.go
- restful_test.go
SNOW-1754426 While migrating from Nginx to Envoy it was observed that when session expired and request was retried after renewal, `requestId` and `request_guid` params where duplicated. The reason was that headers were added to existing value list instead of being replaced.
> SNOW-1754426 Fix duplicated requestId and request_guid params

- encrypt_util.go
- encrypt_util_test.go
- storage_client.go
SNOW-1524257 Implemented GCM encryption to be ready for CSP integrations.
> SNOW-1524257 Implement GCM encryption

- encrypt_util.go
- encrypt_util_test.go
SNOW-1569290 Fixes to use 12 bytes for GCM encryption.
> SNOW-1569290 Use 12 bytes for IV in gcm

- azure_storage_client.go
- util.go
- util_test.go
SNOW-1569290 Azure client treated headers as case sensitive before, which causes fails when downloading files uploaded by other drivers.
> SNOW-1569290 Make Azure headers case insensitive

- connection_util.go
SNOW-1760222 This change introduces raising PUT/GET errors by default - they can be silenced again by configuring file transfer.
> SNOW-1760222 Raise PUT/GET errors by default

- auth_test.go
- connection.go
SNOW-1806123 It is a bit of reversion of https://github.com/snowflakedb/gosnowflake/pull/1196 . Firstly, the issue was that we persisted a auth context in `snowflakeConn` and reused it in closing. But if the context was cancelled or timed out, it ended up in problems with closing connection. After 1196 context was not propagated to auth calls so auth calls couldn't have been cancelled or timed out. Now the context is propagated to auth calls again, but it is not used during session closing.
> SNOW-1806123 Propagate context to snowflakeConn

- connection_util.go
Currently, if the user sets the OCSP cache server URL
```
SF_OCSP_RESPONSE_CACHE_SERVER_URL
```
it is never respected and always overwritten.
This commit only sets the OCSP env vars if they are not already set by the user.
> Ignore setting OCSP env if already set

- driver_test.go
> NO-SNOW Add more logging to TestLargeSetResultCancel

- async.go
- chunk_test.go
- connection.go
- errors.go
- rows.go
SNOW-1854661 Detect JSON response in Arrow batches mode and return error instead of panic.
> SNOW-1854661 Detect JSON response in Arrow batches mode and return error

- doc.go
The heading wasn't being rendered: https://pkg.go.dev/github.com/snowflakedb/gosnowflake
Added a missing newline.
> fix connection Config Config heading

- structured_type_read_test.go
NO-SNOW some tests started failing because select didn't have `order by` clause.
> NO-SNOW Fix tests which were lacking order by clause

- auth.go
- secure_storage_manager.go
- secure_storage_manager_test.go
- util_test.go
SNOW-1825790 Separate secure storage managers to make them easier to extend.
> SNOW-1825790 Separate secure storage managers based on file and keyring

- .github/workflows/build-test.yml
- ci/test.bat
- ci/test.sh
- test_data/wiremock/mappings/select1.json
- test_data/wiremock/mappings/telemetry.json
- wiremock_test.go
SNOW-921006 Introduce wiremock
> SNOW-921006 Introduce wiremock

- auth.go
Being able to see what claims are used inside JWT is immensely useful for troubleshooting issues with such authentication type, and can even one-shot certain types of issues (wrong key used, wrong login_name used, etc.). 
It would be equally useful having in gosnowflake too. Even more useful, since it would also help Snowflake Terraform Provider issues which trace back to keypair authentication.
No auth logic was changed, all the change is doing is to add two additional loglines, one of which logs out the JWT claims for the token generated.
> NO-SNOW log JWT claims on debug loglevel

- go.mod
- go.sum
Addresses [CVE-2025-30204](https://www.cve.org/CVERecord?id=CVE-2025-30204)
* https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGOLANGJWTJWTV5-9510922
* https://github.com/snowflakedb/gosnowflake/issues/1341
> SNOW-2002049 CVE-2025-30204 bump jwt 5.2.1 -> 5.2.2

- driver_ocsp_test.go
- ocsp.go
- ocsp_test.go
- test_data/wiremock/mappings/auth/password/successful_flow.json
- test_data/wiremock/mappings/ocsp/malformed.json
- test_data/wiremock/mappings/ocsp/unauthorized.json
- wiremock_test.go
SNOW-1958566 PR provides change to not fallback to GET OCSP request unless POST returns malformed response. PR provides also simple OCSP test server.
> SNOW-1958566 Do fallback for OCSP GET request only when malformed response for POST is returned

- auth.go
- auth_test.go
SNOW-1825500 Add OAUTH_TYPE to login request
> SNOW-1825500 Add OAUTH_TYPE to login request

- os_specific_posix.go
- os_specific_windows.go
- secure_storage_manager.go
- secure_storage_manager_test.go
- util_test.go
SNOW-1825790 Implement safer file based token cache
> SNOW-1825790 Implement safer file based token cache

- auth.go
- auth_test.go
SNOW-1825476 Removed rewriting password to token field for PAT authentication.
> SNOW-1825476 Remove PAT with password instead of token

- auth_with_oauth_okta_client_credentials_test.go
SNOW-2026797 ClientCredential typo fix
> SNOW-2026797 Test naming fix

- driver_test.go
- structured_type_write_test.go
NO-SNOW Add missing parameter to structured types tests + reorganize order of initialization of these tests.
> NO-SNOW Enable structured types in FDN tables in tests

- encrypt_util.go
- encrypt_util_test.go
SNOW-2062018 Fixed smkId that was cast to `int` type, which was system dependent.
> SNOW-2062018 Fix smkId downcast to int

- gcs_storage_client.go
- gcs_storage_client_test.go
SNOW-2032700 Please explain the changes you made here.
> SNOW-2032700 Go driver support virtual-style domains(3)

- arrow_test.go
- bindings_test.go
- converter.go
- converter_test.go
- driver_test.go
- old_driver_test.go
- rows.go
- rows_test.go
SNOW-2091309 Before this change, when `NUMBER(19, 0)` was used as a column, there was a potential loss of precision when the value was above 9,223,372,036,854,775,807 (max int64 value). To fix this issue, `*big.Int` or string (depending on the higher precision setting) is pessimistically chosen as the return type for such a column.
Also, added higher precision support for JSON result sets.
> SNOW-2091309 Fix precision lost for NUMBER(19, 0) by returning big.Int and for non-zero scale numbers, align scan types and actual types

- telemetry.go
Access to the slices length must be protected by the mutex, but isn't. Running a test with the race detector would show the problem clearly.
Background: We are facing a large amount of memory usage that stems from the error telemetry framework of gosnowflake. It could be a leak, but it is unclear what it exactly is. While digging through the code, we found this potential issue. Most likely not
the cause of the memory growth, but good to fix in any case.
> Fix unprotected concurrent access to slice

- connection_configuration.go
- connection_configuration_test.go
- test_data/connections.toml
The Go driver currently doesn't support reading snake_case parameters from connection configuration files (e.g., connections.toml). This is problematic in Snowpark Container Services (SPCS) where connection parameters are automatically generated in snake_case format, preventing the use of auto-configuration features.
Modified the connection parameter parsing logic to handle both camelCase and snake_case parameter names. This change maintains backward compatibility with camelCase while adding support for snake_case variants, enabling seamless auto-configuration in SPCS environments.
For example:
- `client_timeout` and `clientTimeout`
- `login_timeout` and `loginTimeout`
- `disable_ocsp_checks` and `disableOcspChecks`
> SNOW-2135451 Support snake_case connection parameters

- auth_oauth.go
- auth_oauth_test.go
- dsn.go
- dsn_test.go
- test_data/wiremock/mappings/oauth2/authorization_code/successful_flow_with_single_use_refresh_token.json
SNOW-2113973 This PR introduces support for opt-in change of refresh token type returned from Snowflake IdP during OAuth authentication. With the flag enabled, the refresh token will be single-use instead of time-valid.
> SNOW-2113973: Add support for opt-in single use refresh token in OAuth flow

- crl.go
- crl_test.go
SNOW-2117152 Adds the mechanism to cleanup CRL caches.
> SNOW-2117152 Add CRL cache cleanup

- priv_key_test.go
NO-SNOW Remove failing and blocking test of keypair auth. We are migrating to have all tests using keypairs.
> NO-SNOW Remove TestJWTAuthentication

- connection.go
- crl.go
- crl_test.go
- doc.go
- dsn.go
- dsn_test.go
SNOW-2117152 Moves CRL cleanup to singleton, to not be triggered for each connection
> SNOW-2117152 Move CRL cleanup to singleton

- .cursor/rules/overall-guidelines.mdc
- .cursor/rules/testing.mdc
- Makefile
- assert_test.go
- auth_oauth.go
- auth_wif.go
- azure_storage_client.go
- cmd/arrow/Makefile
- connection.go
- connection_configuration_test.go
- connection_test.go
- connectivity_diagnosis.go
- connectivity_diagnosis_test.go
- crl.go
- dsn.go
- dsn_test.go
- errors.go
- gcs_storage_client.go
- go.mod
- ocsp.go
- rows_test.go
- s3_storage_client.go
- tls_config.go
- tls_config_test.go
- transport.go
- transport_test.go
This PR adds support for custom TLS configurations while preserving Snowflake's certificate revocation checking (OCSP/CRL). Users can now register custom TLS configs with their own root CAs, client certificates, and verification callbacks, which will be automatically chained with Snowflake's security validation.
Configs each have a name and are registered; the `tlsConfigName` parameter in the DSN can be used to reference them.
```go
import (
"crypto/x509"
"database/sql"
_ "github.com/snowflakedb/gosnowflake"
)
// Register custom TLS config with your root CAs
rootCertPool := x509.NewCertPool()
pem, _ := os.ReadFile("/path/to/ca-cert.pem")
rootCertPool.AppendCertsFromPEM(pem)
err := gosnowflake.RegisterTLSConfig("myCustomTLS", &tls.Config{
RootCAs: rootCertPool,
})
if err != nil {
// handle …
```
> SNOW-2176203: Add RegisterTLSConfig support

- ci/container/test_authentication.sh
- structured_type_read_test.go
NO-SNOW Fixed tests that failed on inconsistent order of returned rows.
> NO-SNOW Fix structured types tests on Jenkins

- assert_test.go
- put_get_test.go
NO-SNOW Previously this test, when query failed, paniced due to using `t.Error` instead of `t.Fatal`.
> NO-SNOW Fix panic in testPutGet

- azure_storage_client.go
- azure_storage_client_test.go
- connection_configuration_test.go
- connection_util.go
- file_transfer_agent.go
- file_transfer_agent_test.go
- gcs_storage_client.go
- gcs_storage_client_test.go
- local_storage_client_test.go
- put_get_test.go
- s3_storage_client.go
- s3_storage_client_test.go
- storage_client.go
SNOW-2294562
This PR contains the following changes:
1. Pass the `parallel` parameter to S3/Azure's download API to enable multi-part download on each file.
2. Implement multi-part parallel download for GCP which utilizes the same parameters as S3 and Azure.
3. Use `meta.options.MultiPartThreshold` as the part size when calling S3/Azure's download API. This matches the behavior of the PUT command for S3 ([link](https://github.com/snowflakedb/gosnowflake/blob/858561dce1e02cd839bc2ad2e57a2c396ace14b8/s3_storage_client.go#L213)).
4. Updated tests.
Tested [put_get_test.go](https://github.com/snowflakedb/gosnowflake/pull/1549/files#diff-a3eaa8612e5469f8b99e45b5d4a7c02fc11925993c07205b069fb6a6032c10df) against both AWS and Azure deployments.
> SNOW-2294562: Change GET to do multi-part parallel download for S3, Azure, and GCP

- converter.go
- converter_test.go
- crl_test.go
NO-SNOW Fixes memory allocation used when parsing numbers to big.Float (for JSON response, when `WithHigherPrecision` was used). Previously every big.Float occupied ~1GB of memory, now it is a manitude of bytes.
> NO-SNOW Limit big.Float parsing memory

- auth_oauth.go
SNOW-2231891 Logs warn on using HTTP protocol in OAuth
> SNOW-2231891 Log warn on using HTTP protocol in OAuth

- crl_test.go
NO-SNOW Skip TestCRLE2E on Jenkins, because tests on Jenkins don't use HTTPS.
> NO-SNOW Skip TestCRLE2E on Jenkins

- connection.go
- connection_util.go
- doc.go
- heartbeat.go
- heartbeat_test.go
SNOW-2334860 
Add support for the CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY parameter which enables us to configure how ofter a heartbeat requests is emited by the client. 
In the existing implementation, a default of 60 min is used, which is too high for SPCS.  The refresh rate there is 30 min.
> SNOW-2334860: Add support for CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY
