auth.go, cmd/select1/Makefile, converter.go, driver.go, driver_test.go, dsn.go, errors.go, restful.go
=> added OKTA support. NOTE: no MFA support is included

README.md
fixed README about the sample code name
=> fixed README about the sample code name

README.md
=> fixed the link to code cove

.travis.yml, Makefile, retry.go, rows.go
Added -race option to test. Issue #60
=> fixed race condition errors

.travis.yml
=> added tip build and tests

README.md, cmd/verifycert/Makefile, cmd/verifycert/verifycert.go, connection.go, driver.go, driver_test.go, glide.lock, ocsp.go, restful.go, retry.go, rows.go
Added the certificate revocation check with OCSP
=> Added the certificate revocation check with OCSP

README.md
I pulled these out of the switch in `dsn.parseDSNParams`. I didn't include `account`, `database`, or `schema` because they are in the body of the DSN.
=> Mention the available parameters for the DSN.

connection.go, datatype_test.go, driver_test.go, dsn_test.go, location_test.go, ocsp.go, util.go, util_test.go
=> added util_test.go

connection.go, converter.go, converter_test.go, datatype.go, datatype_test.go, driver_test.go, errors.go, util_test.go
More tests coverages. Remove unused codes.
=> More tests coverages

location_test.go
=> add more tests for Location

connection.go, driver.go, driver_test.go, dsn.go, dsn_test.go, location_test.go
=> More Tests

auth.go, authokta.go, restful.go
moved OKTA related auth to authokta.go
=> moved OKTA related auth to authokta.go

auth.go, authokta.go, connection.go, ocsp.go, ocsp_test.go, restful.go, retry.go, retry_test.go, util.go, util_test.go
refactored and added more tests
=> refactored and added more tests

README.md, auth.go, authokta.go, connection.go, driver.go, dsn.go, ocsp.go, ocsp_test.go, restful.go, retry.go, retry_test.go, util.go, util_test.go
=> Proxy support

connection.go, driver_test.go, rows.go, rows_test.go
fixed large result set fetch. Issue #80
=> fixed large result set fetch. Issue #80

README.md, connection.go, driver_test.go, dsn.go, errors.go, ocsp_test.go, retry_test.go, rows.go, rows_test.go
=> Added test cases for downloadChunk with errors

auth.go, authokta.go, connection.go, driver.go, driver_test.go, errors.go, restful.go, restful_test.go, retry_test.go, rows.go, rows_test.go
Added test cases for Restful related funcs
=> Added test cases for Restful related funcs

connection.go, driver_test.go, errors.go, transaction.go
implemented ResultNoRows for DDL
=> implemented ResultNoRows for DDL

auth.go, auth_test.go, authokta.go, authokta_test.go, connection.go, converter.go, driver.go, driver_test.go, errors.go, restful.go, restful_test.go, rows.go, statement.go
=> Implemented BeginTx, NextResultSet HasNextResultSet, and added more tunit ests

ocsp.go, ocsp_test.go
=> Added more ocsp tests

ocsp.go, ocsp_test.go
=> more ocsp tests

driver_test.go, ocsp.go, ocsp_test.go
=> Binding TIMESTAMP_TZ support

auth.go, authokta.go, converter.go, driver_test.go, restful.go, rows.go
added glog.Flush to all error logs
=> added glog.Flush to all error logs

auth.go, authokta.go, connection.go, converter.go, errors.go, errors_test.go, location.go, restful.go, rows.go, sqlstate.go
Added client side SQLState codes
=> Added client side SQLState codes

authokta_test.go
added more unit tests for authokta.go
=> added more unit tests for authokta.go

auth.go, auth_test.go, connection.go, driver.go, driver_test.go, dsn.go, query.go, restful.go
=> populate session parameters

auth.go, authokta.go
=> Fixed typo in parameter

README.md
Updated the doc for preview release
- [] Run ``make fmt`` to fix inconsistent formats
=> Updated the doc for preview release

README.rst
=> recovered travis-ci and codecov links

benchmark/largesetresult/Makefile, benchmark/largesetresult/README.rst, benchmark/largesetresult/largesetresult_test.go
=> added profile and trace commands

README.rst, benchmark/largesetresult/largesetresult_test.go, cmd/select1/select1.go, cmd/selectmany/selectmany.go, driver_test.go, errors.go, restful.go, retry.go, rows.go
As agreed in #115, updating doc, sample codes and tests.
Code reviews are welcome.
=> PR 115 and doc updates

.travis.yml, cmd/showparam/.gitignore, cmd/showparam/Makefile, cmd/showparam/showparam.go, doc.go, dsn.go, dsn_test.go
DSN supports session parameters
=> Added session parameter support in DSN

version.go
Forgot to update the version number in version.go
=> Fixed version number

version.go
=> bumped up version to 1.1.1

CHANGELOG.md, version.go
=> bumped up version to 1.1.2

README.rst
=> added dep ensure requirement

auth.go, driver_test.go, dsn.go, dsn_test.go
- Removed hardcoded PUBLIC schema name in case only DB is specified
- Fixed request ID value in authentication
=> Removed hardcodd PUBLIC schema name in case only DB is specified

README.rst
Trivial, added some documentation about a test dependency
=> Adds documentation about jq test dependency

auth.go, auth_test.go, driver.go
This is a followup to an earlier PR. The authenticator connection parameter should be used in auth.go, rather than inferring the authenticator from the values passed in.
Tested via setting connection parameters in `parameters.json` and running `make test`.
=> Cleanup of auth.go

doc.go
Documents recently added authenticators.
=> Documents recently added authenticators

CHANGELOG.md, version.go
=> Bumping up version to v1.1.5

auth.go, authexternalbrowser.go, authokta.go
Updated OS info in the session.
=> Added OS info to the session

gosnowflake.mak
Workaround golint issue in #161
=> workaround for golint missing issue

doc.go, version.go
=> Updated doc for client_session_keep_alive option. Bumped up version to 1.1.7

CHANGELOG.md, README.rst, version.go
=> Prep 1.1.8

gosnowflake.mak
=> Fixed typo. megacache => megacheck

ocsp.go
=> Fix proxy settings

CHANGELOG.md, doc.go, version.go
=> Updated doc for v1.1.11

auth.go, auth_test.go, authokta.go, authokta_test.go, cmd/externalbrowser/externalbrowser.go, driver.go, dsn.go, dsn_test.go, errors.go, priv_key_test.go, restful.go, version.go
=> Prep 1.1.19

CHANGELOG.md, Makefile, auth.go, chunk.go, converter.go, driver.go, dsn.go, dsn_test.go, gosnowflake.mak, ocsp.go, ocsp_test.go, query.go
=> Snow 76958 1.2.0

auth.go, connection.go, doc.go, driver.go, driver_test.go, dsn.go, dsn_test.go, errors.go, ocsp.go
The default behavior is to enable validation;
=> SNOW-75649 Add a flag to control parameter check.

auth.go, authokta.go, authokta_test.go, driver.go, gosnowflake.mak, heartbeat.go, ocsp.go, ocsp_test.go, restful.go, restful_test.go, retry.go, retry_test.go, rows.go
Send clientStartTime and retryCount with each /queries/v1/query-request
=> Snow 80090

connection.go, connection_test.go, restful.go, restful_test.go
https://github.com/snowflakedb/gosnowflake/pull/257 for prep-1.3.1
=> Snow 92880 pr

retry.go
=> Snow 90775 pr2

retry.go
SNOW-90775: no retry for expired certificate
=> SNOW-90775: no retry for expired certificate

Makefile, auth.go, authokta.go, authokta_test.go, benchmark/jsonresultset/jsonresultset_test.go, benchmark/largesetresult/largesetresult_test.go, cmd/selectmany/selectmany.go, connection.go, connection_test.go, doc.go, driver.go, driver_ocsp_test.go, driver_test.go, dsn_test.go, errors.go, gosnowflake.mak, heartbeat.go, ocsp.go, ocsp_test.go, restful.go, restful_test.go, retry.go, retry_test.go, rows.go, scripts/hang_webserver.py, version.go
=> Prep 1.3.1

.travis.yml, README.rst, driver_test.go, ocsp_test.go
=> Test PR for #266

.travis.yml, README.rst, driver_ocsp_test.go, driver_test.go, ocsp.go, ocsp_test.go, query.go, rows.go, version.go
=> Prep 1.3.2

doc.go
I added information about the NO_PROXY environment variable.
- [Y] Extended the README / documentation, if necessary
=> SNOW-89018: Updated doc about NO_PROXY

.github/actions/gajira-create/README.md, .github/actions/gajira-create/action.js, .github/actions/gajira-create/action.yml, .github/actions/gajira-create/common/net/Jira.js, .github/actions/gajira-create/common/net/client.js, .github/actions/gajira-create/dist/index.js, .github/actions/gajira-create/index.js, .github/actions/gajira-issue-update/action.js, .github/actions/gajira-issue-update/action.yml, .github/actions/gajira-issue-update/dist/index.js, .github/workflows/jira_comment.yml, .github/workflows/jira_issue.yml
Add gh actions for jira integration
=> SNOW-135600 add actions

.github/actions/gajira-create/README.md, .github/actions/gajira-create/action.js, .github/actions/gajira-create/action.yml, .github/actions/gajira-create/common/net/Jira.js, .github/actions/gajira-create/common/net/client.js, .github/actions/gajira-create/dist/index.js, .github/actions/gajira-create/index.js, .github/actions/gajira-issue-update/action.js, .github/actions/gajira-issue-update/action.yml, .github/actions/gajira-issue-update/dist/index.js, .github/workflows/jira_comment.yml, .github/workflows/jira_issue.yml, authexternalbrowser.go, authokta.go
No session/master token is found
=> Remove raw response body logging during okta and external browser authentication

.github/actions/gajira-create/README.md, .github/actions/gajira-create/action.js, .github/actions/gajira-create/action.yml, .github/actions/gajira-create/common/net/Jira.js, .github/actions/gajira-create/common/net/client.js, .github/actions/gajira-create/dist/index.js, .github/actions/gajira-create/index.js, .github/actions/gajira-issue-update/action.js, .github/actions/gajira-issue-update/action.yml, .github/actions/gajira-issue-update/dist/index.js, .github/workflows/jira_comment.yml, .github/workflows/jira_issue.yml, dsn.go, dsn_test.go
Before, the DSN function wasn't actually adding InsecureMode to the string. Update so it does if insecuremode is true
=> Snow 146214/add insecure mode to dsn

.github/workflows/jira_issue.yml
UPdate the area for auto-created jira issues
=> SNOW-153244 jira area

authexternalbrowser.go, authokta.go, doc.go, dsn.go, dsn_test.go, version.go
=> Prep 1.3.5

.github/workflows/build-test.yml, ci/scripts/wss.sh
This updates the Whitesource Project and Product names.
- [] Created tests which fail without the change (if possible)
=> updated whitesource project and product names

.github/workflows/build-test.yml
Fix the test schedule.
- [] Created tests which fail without the change (if possible)
=> Fixed the schedule

converter.go, converter_test.go, driver_test.go, query.go, rows.go
=> Update Arrow Interface Scan Behavior

ci/scripts/wss.sh
=> Update wss naming convensions

ci/scripts/wss.sh
=> fixed master wss

version.go
=> Version Bump to 1.3.6

ocsp_test.go
=> SNOW-177315 Fix OCSP Cache Timestamps

.github/workflows/semgrep.yml, .semgrep.yml
Details, please refer to confluence page: 
https://snowflakecomputing.atlassian.net/wiki/spaces/CLO/pages/1127055936/Semgrep+Handbook
=> add semgrep check

.github/workflows/build-test.yml, doc.go, go.mod, ocsp.go, ocsp_test.go
=> Support Go v1.15

version.go
=> Did Version Bump to 1.3.8

connection.go, converter.go, converter_test.go, driver_test.go, query.go
=> SNOW-177692 Simple array binding

version.go
=> Bump GoSnowflake version to 1.3.9

doc.go
SNOW-190226
Document array binding support for the Go connector.
=> SNOW-190226 Document array binding support for the Go connector

version.go
=> Version Bump Go Connector to 1.3.10

authexternalbrowser.go, connection.go
Fixed temporary by using the channels
=> SNOW-221819 externalbrowser not working

auth.go, authexternalbrowser.go, authokta.go, chunk_arrow.go, cmd/logger/logger.go, connection.go, ctx_test.go, driver.go, location.go, log.go, ocsp.go, restful.go, retry.go, rows.go, statement.go, transaction.go
Add WithContext support for logging to record context fields. Add session ID in context.
=> SNOW-239637 Logging with context

version.go
=> SNOW-274797: Bumped up GoLang connector MINOR version from 1.3.13 to 1.4.0

driver.go, dsn.go
https://github.com/snowflakedb/gosnowflake/pull/376
=> SNOW-273060 Set Transport Timeout

doc.go
Added documentation about asynchronous queries.
- [+] Extended the README / documentation, if necessary
=> SNOW-281014: Document asynchronous SQL in the Go Snowflake Driver.

bind_uploader.go, bindings_test.go, connection.go, connection_test.go, converter.go, converter_test.go, datatype.go, datatype_test.go, doc.go, driver_test.go, prepared_statement_test.go, rows.go
Refactor type converters to allow for array binding.
=> SNOW-158369 Refactor Type Converter

version.go
=> SNOW-294007: Bumped up GoLang connector PATCH version from 1.4.0 to 1.4.1

azure_util.go, file_compression_type.go, file_transfer_agent.go, file_util.go, gcs_util.go, s3_util.go
Remote storage utils using 3rd party software skeletons
=> SNOW-29352 Add Remote Storage Utils

auth.go, auth_test.go
SNOW-209081
Description
Introduce a no-op authentication type that bypasses the actual authentication
by grabbing the auth token and session from the existing token accessor.
Testing
add new unit test case to verify that post auth http call is not made when auth type is token accessor
=> SNOW-209081 Allow bypass authentication by re-using token from accessor

auth.go, authexternalbrowser.go, authokta.go, connection.go, connection_test.go, heartbeat.go, ocsp.go, restful.go
Change user agent header to conform to RFC 7231.
=> SNOW-95626 User Agent Headers

auth.go, chunk_downloader.go, connection.go, connection_test.go, driver.go, errors.go, query.go, restful.go, rows.go, statement_test.go, util.go
With a query Id provided in context to fetch the results of that query.
=> SNOW-212951 Fetch query result with query Id

version.go
=> SNOW-329852: Bumped up GoLang connector PATCH version from 1.4.1 to 1.4.2

connection.go, connection_test.go, doc.go, driver.go, restful.go, statement_test.go, util.go
Update documentation regarding checking query status of asynchronous queries.
=> Update Polling Documentation for Async Queries

azure_util.go, bind_uploader.go, bindings_test.go, connection.go, driver.go, driver_test.go, encrypt_util.go, encrypt_util_test.go, file_compression_type.go, file_transfer_agent.go, file_util.go, gcs_util.go, local_util.go, put_get_test.go, put_get_user_stage_test.go, put_get_with_aws_test.go, s3_util.go, s3_util_test.go, storage_client.go, util.go
S3 PUT and streaming PUT implementation.
PUT documentation: https://docs.snowflake.com/en/sql-reference/sql/put.html
Streaming PUT: use WithFileStream() method to pass file pointer to be read for PUT
Dependencies: https://github.com/snowflakedb/gosnowflake/pull/404
=> SNOW-294154 S3 PUT Support

version.go
=> SNOW-350730: Bumped up GoLang connector PATCH version from 1.4.2 to  1.4.3

version.go
Co-authored-by: Jenkins User <snowflake-provisioner>
=> SNOW-350730: Bumped up GoLang connector PATCH version from 1.4.2 to 1.4.3

.github/workflows/build-test.yml
=> SNOW-355681 Add Support for Go 1.16

version.go
=> SNOW-360818: Bumped up GoLang connector MINOR version from 1.4.3 to 1.5.0

connector_test.go, storage_client.go
make lint failing due to staticcheck update regarding ineffective assignment
=> Fix StaticCheck Error

doc.go
=> SNOW-362342 Typo and Formatting Fix in Docs

bindings_test.go
Bulk array binding support -- default array bind becomes bound by streaming PUT (for supported cloud vendors) if the number of bind exceeds the default number (currently 65280).
Internal documentation: https://snowflakecomputing.atlassian.net/wiki/spaces/~724606231/pages/2071922377/The+Definitive+Guide+to+Binding+in+the+Golang+Driver
=> SNOW-48673 Bulk Array Binding Support

azure_util.go, bind_uploader.go, driver_test.go, encrypt_util.go, file_transfer_agent.go, gcs_util.go, put_get_test.go, put_get_with_azure_test.go, put_get_with_gcp_test.go, s3_util.go, util.go
PUT & streaming PUT support for Azure/GCP
=> SNOW-294155 Azure/GCP PUT Support

doc.go
=> Update PUT Documentation

doc.go
Added info about binding arrays that are large enough to use batching.
=> Mgilkey snow364349 golang batch insert

version.go
=> SNOW-370737: Bumped up GoLang connector PATCH version from 1.5.0 to 1.5.1

connection.go, connection_test.go, dsn.go, restful.go, telemetry.go, telemetry_test.go
=> SNOW-81453 Inband Telemetry

async_test.go, bindings_test.go, chunk_downloader.go, chunk_test.go, connection_test.go, doc.go, driver_test.go, file_transfer_agent.go, multistatement_test.go, old_driver_test.go, priv_key_test.go, rows_test.go, statement_test.go
Archiving old tests after Arrow GA. Will merge PR (pending) that enables a client side parameter guard and when the server side PR making Arrow the default as per v1.6.0 and deployed.
=> SNOW-278596 Archive Old Tests

version.go
Co-authored-by: Jenkins User <snowflake-provisioner>
=> SNOW-396457: Bumped up GoLang connector MINOR version from 1.5.1 to 1.6.0

doc.go
=> SNOW-54757: Improve wording to make a sentence more clear.

azure_util.go, bind_uploader.go, bindings_test.go, encrypt_util_test.go, file_transfer_agent.go
=> SNOW-403403 Multi-Part Bind Upload

doc.go
SNOW-414875
Summary of changes:
* Adding documentation about support for GET command.
* Minor revisions to the PUT documentation
Testing: local HTML build to check presentation and clarity
y
=> SNOW-414875 Add GET documentation for Golang

async_test.go, bindings_test.go, chunk_downloader.go, driver_test.go, encrypt_util_test.go, file_transfer_agent.go, put_get_test.go
Remove ARROW statements for testing after GA
=> SNOW-407167 Remove Arrow Force Statements

version.go
=> SNOW-429645 Version Bump from 1.6.0 to 1.6.1

connection.go, connection_test.go, ocsp.go
Add privatelink revocation check when building connection.
=> SNOW-365916 Add Privatelink Revocation Check

ci/scripts/wss.sh, debug.go, go.sum, priv_key_test.go, priv_key_test_coding_helper.go, release.go, secret_detector.go
Pinned whitesource version to 21.7.2
=> Update Whitesource Scan Version

version.go
=> SNOW-458857 Version Bump GoLang driver from 1.6.1 to 1.7.0

connection.go
Fixes to issues raised in QueryStatus
=> SNOW-468042 Fix QueryStatus Panic

connection_util.go, errors.go, telemetry.go
Add source to telemetry in line with other drivers/connectors in Snowhouse. Viewable under client_telemetry_v.
=> SNOW-502094 Add Source to Telemetry

connection_util.go, errors.go, telemetry.go, version.go
=> Snow 502079 golang connector version bump

connection_util.go, errors.go, telemetry_test.go
Updated nano to mili for timestamp in telemetry
=> SNOW-502458 Fix Telemetry Timestamp

version.go
=> SNOW-518497 Prep 1.6.5

bind_uploader.go, put_get_test.go, put_get_with_aws_test.go, s3_util.go
Fix error where nested files in s3 stages were not returning the proper file.
=> SNOW-522730 Fix S3 GET in Nested Stage

auth.go, bind_uploader.go, connection_test.go, driver_test.go, go.mod, heartbeat.go, monitoring.go, restful.go, restful_test.go, retry.go, util.go, util_test.go, uuid.go
Implement UUID https://github.com/snowflakedb/gosnowflake/issues/173
=> SNOW-440362 Implement UUIDv4

connection_test.go, errors.go, monitoring.go
Change ErrorCode to type string
=> SNOW-535399 Fix GetQueryStatus Bug

chunk_downloader.go, connection.go, connection_util.go
=> Formatting & Lint

arrow_test.go, connection_util.go, converter.go, location.go
Fixes https://github.com/snowflakedb/gosnowflake/issues/523.
=> SNOW-526255 Fix Time Scale for Arrow

auth.go, bind_uploader.go, connection_test.go, converter.go, converter_test.go, doc.go, driver_ocsp_test.go, driver_test.go, heartbeat.go, monitoring.go, ocsp.go, put_get_test.go, restful.go, restful_test.go, retry.go, util.go, util_test.go, uuid.go
Fixes https://github.com/snowflakedb/gosnowflake/issues/552
=> SNOW-546088 Export UUID

arrow_chunk.go, chunk_downloader.go, connection_util.go, converter.go, converter_test.go, location.go, rows.go
Fix crash when location cannot be parsed for whatever reason. Add another safeguard when parsing timestamp_ltz as well.
=> SNOW-563221 Fix Missing Locale

version.go
=> SNOW-594139 Bump Up Golang version to 1.6.10

bind_uploader.go, connection.go, telemetry_test.go
Simba ticket 00390103
Fixes #613 where the connection parameter DisableTelemetry is ignored.
=> SNOW-623421 Fixes DisableTelemetry to disable telemetry when it is true

chunk_downloader.go, retry.go
Enhance logs for chunk downloading to collect more information.
=> Add more details to logs for downloading

connection.go, connection_test.go, monitoring.go, ocsp.go, telemetry.go
Tests https://github.com/snowflakedb/gosnowflake/pull/650
=> Fix Goroutine Leak

driver_test.go, file_transfer_agent.go, gcs_storage_client.go, put_get_test.go
For https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/94
=> Support using gcs downscoped token for GET/PUT statements instead of presigned urls

storage_client.go
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/299
#701
=> SNOW-724764 Log error to avoid silent failure for PUT operation

authokta.go
Add support for new OKTA OIE
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/179
=> Add support for OKTA OIE

.github/workflows/cla_bot.yml
=> SNOW-829489: Fix CLA Assistant Github Action

cmd/multistatement/.gitignore, cmd/multistatement/Makefile, cmd/multistatement/multistatement.go
=> SNOW-829187 Add multistatement query example

cmd/logger/Makefile, cmd/mfa/Makefile
=> Add missing makefiles for example apps

cmd/multistatement/multistatement.go
=> Add multistatement exec example

version.go
=> SNOW-838450_golang_connector_version_bump

cmd/arrow/.gitignore, cmd/arrow/batches/Makefile, cmd/arrow/batches/arrow_batches.go
=> SNOW-832885 Add arrow_batches example

cmd/multistatement/multistatement.go
=> Fix multistatement demo omitting first result set

go.mod, go.sum
=> SNOW-840123 Upgrade arrow 12.0.0 -> 12.0.1

cmd/distributedfetch/.gitignore, cmd/distributedfetch/Makefile, cmd/distributedfetch/distributedfetch.go
=> SNOW-853914 Add distributed fetch example

connection.go, doc.go
Fix the async example in documentation.
=> SNOW-832825: Fix async documentation

auth.go, auth_test.go, ci/scripts/hang_webserver.py, driver_ocsp_test.go, priv_key_test.go, restful.go, restful_test.go, retry.go, retry_test.go, test_util.go
=> SNOW-833537 Each time retry keypair auth with new token

.github/workflows/snyk-pr.yml
=> SNOW-871839: Fix Snyk permissions

statement_test.go
=> Enable procedure calling test

doc.go
=> SNOW-833537 Add JWT retry docs

arrow_test.go, async_test.go, bindings_test.go, chunk_test.go, driver_test.go, file_transfer_agent_test.go, multistatement_test.go, old_driver_test.go, prepared_statement_test.go, put_get_test.go, put_get_user_stage_test.go, put_get_with_aws_test.go, rows_test.go, statement_test.go
=> SNOW-859548 Refactor runTests to runDBTest

.github/workflows/build-test.yml, README.md
Upload code coverage files from Github action runs to code cov which calculates an average.
18 files are uploaded; for the combination of each OS, version and cloud provider. Code cov will merge the files.
https://app.codecov.io/gh/snowflakedb/gosnowflake/commit/43f021f4593d1ada3290a56aa2361e4ebc804372
=> SNOW-870356: Integrate code coverage with CodeCov

doc.go
Added docs about https://github.com/snowflakedb/gosnowflake/pull/874
=> SNOW-845282: Add docs about tmpDirPath

connection_test.go
=> SNOW-894815: Disable TestConcurrentReadOnParams

azure_storage_client_test.go, gcs_storage_client_test.go, ocsp_test.go, put_get_test.go, put_get_user_stage_test.go, put_get_with_aws_test.go, s3_storage_client_test.go
=> [SNOW-892549] Remove references to sfcdev1

version.go
=> SNOW-897024: Bumped up GoLang connector PATCH version from 1.6.23 to 1.6.24

.github/workflows/snyk-issue.yml, .github/workflows/snyk-pr.yml
=> SNOW-898353 Fix snyk permissions

README.md
Explained how to init project.
=> SNOW-905755: Update doc - add init section

auth_test.go, chunk_test.go, connection_test.go, converter_test.go, driver_test.go, file_transfer_agent_test.go, heartbeat_test.go, htap_test.go, multistatement_test.go, put_get_with_aws_test.go, rows_test.go, telemetry_test.go
=> SNOW-911146  Extract method of preparing connection in tests

async.go, authokta.go, chunk_downloader.go, client.go, client_test.go, connection.go, connection_test.go, heartbeat.go, monitoring.go, ocsp.go, ocsp_test.go, restful.go, restful_test.go, retry.go, retry_test.go, telemetry.go, telemetry_test.go, util.go, util_test.go
Introducing retry reason and retry count parameters.
=> SNOW-736353: Implement retry reason

version.go
=> SNOW-921830: Bumped up GoLang connector PATCH version from 1.6.24 to 1.6.25

codecov.yml
=> SNOW-859636 Add codecov.yml with partials_as_hits parameter

.github/workflows/jira_comment.yml
=> SNOW-859636 Exclude codecov[bot] from Jira Issue comments

.github/workflows/jira_comment.yml
=> Snow 859636 codecov jira comment

htap.go
Fixes concurrent access to params from HTAP calls.
=> SNOW-894815 Fix access to params from htap

doc.go
=> add log dependency into doc.go

auth.go
=> fix: error format

assert_test.go
Log the exact location of failing test in assert library
=> [SNOW-856228] Improve assert library

assert_test.go, client_configuration.go, client_configuration_test.go, connection.go, dsn.go, dsn_test.go, easy_logging.go, easy_logging_test.go, errors.go, log.go, log_test.go
=> SNOW-856228 enable easy logging

doc.go
=> SNOW-856228 easy logging documentation

driver_ocsp_test.go, ocsp.go, ocsp_test.go
=> SNOW-961482: Replace OCSP cache with more structured version

ocsp.go
=> SNOW-961482 Cache parsed OCSP response

version.go
=> SNOW-XXX: Bumped up GoLang connector MINOR version from 1.6.25 to 1.7.0

go.mod, go.sum
Upgrade snyk reported library.
=> SNOW-938685 Upgrade net library

version.go
=> PATCH: Bumped up GoLang connector PATCH version from 1.7.0 to 1.7.1

async.go, monitoring.go, rows.go
=> SNOW-976500 Do not drop errors from chunk downloader starting

.github/workflows/build-test.yml
=> SNOW-925280 Add support for go 1.21

go.mod, go.sum
=> SNOW-995607 Upgrade crypto library

version.go
=> PATCH: Bumped up GoLang connector PATCH version from 1.7.1 to 1.7.2

easy_logging.go, easy_logging_test.go
Add mutex to `initTrials` to avoid data race. Resolves #1059 
- Not run: ``make[1]: *** No rule to make target `fmt'.  Stop.``
- Not run: import errors and does not work on `master`
- Creted a test but can't run it since test files have dependencies on other test files with `init` functions that requires me to connect to a real database. I tried to isolate it but had no success. Hopefully a pipeline can confirm the test or I can remove it if it's irrelevant.
- Can't get tests to pass, require account setup, also failing on `master`
- Not necessary
=> fix: Fix data race when initializing logging

version.go
=> MINOR: Bumped up GoLang connector MINOR version from 1.8.0 to 1.9.0

arrow_chunk.go, assert_test.go, chunk_downloader.go, converter.go, converter_test.go, datetime.go, driver_test.go, query.go, rows.go, rows_test.go, structured_type.go, structured_type_test.go
SNOW-1256908 Implementation of structured objects
=> SNOW-1256908 Implement structured objects

assert_test.go, async.go, connection.go, converter.go, converter_test.go, monitoring.go, rows.go, structured_type.go, structured_type_test.go
SNOW-1256916 Implemented structured arrays
=> SNOW-1256916 implement structured arrays

converter.go, datatype.go, structured_type_test.go
SNOW-1256917 Implemented structured maps
=> SNOW-1256917 Implement structured maps

arrow_chunk.go, chunk_downloader.go, converter.go, converter_test.go, rows.go, structured_type.go, structured_type_test.go, util.go
SNOW-1303970 Handling of null values in structured objects and maps
=> SNOW-1303970 Handle null values correctly in structured types

converter.go, query.go, structured_type.go, structured_type_test.go
SNOW-1283946 Handle embedded structured types.
=> SNOW-1283946 Embed structured types

arrow_test.go, converter.go, structured_type_test.go
SNOW-1264786 Support for structured types in arrow batches mode
=> SNOW-1264786 Support structured types in arrow batches

auth.go, connection_util.go, telemetry.go
SNOW-1342971 Add golang version to telemetry and auth requests
=> SNOW-1342971 Add golang version to telemetry and auth request

doc.go
SNOW-1256899 Added docs of structured types usage.
=> SNOW-1256899 Add structured types docs

version.go
=> MINOR: Bumped up GoLang connector MINOR version from 1.9.0 to 1.10.0

auth.go, authokta.go, authokta_test.go, doc.go, dsn.go, dsn_test.go
[issue #942](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/942)
=> SNOW-1226624 Parameter to disable SAML URL check

version.go
=> PATCH: Bumped up GoLang connector PATCH version from 1.10.0 to 1.10.1

doc.go
=> SNOW-1359115 Add info about numbers in arrow batches to docs

.github/workflows/build-test.yml, assert_test.go, bind_uploader.go, connection.go, converter.go, converter_test.go, datatype.go, datetime.go, doc.go, driver_test.go, query.go, structured_type.go, structured_type_read_test.go, structured_type_write_test.go
=> Snow 1460203 structured types inserts

bind_uploader.go, connection.go, converter.go, converter_test.go, datatype.go, doc.go, driver_test.go, query.go, structured_type.go, structured_type_write_test.go
SNOW-1460206 Introduced structrued arrays binding
=> SNOW-1460206 Introduce structured arrays

.github/workflows/build-test.yml
=> SNOW-1342971 Support Golang 1.22

bind_uploader.go, connection.go, converter.go, datatype.go, datetime.go, structured_type.go, structured_type_read_test.go, structured_type_write_test.go
SNOW-1501890 Implemented structured maps
=> SNOW-1501890 Implement structured maps

version.go
=> MINOR: Bumped up GoLang connector MINOR version from 1.10.1 to 1.11.0

structured_type.go, structured_type_read_test.go
Undone some refactoring that caused a regression
=> Fix null in structured types arrays regression

chunk_downloader.go, connection.go
SNOW-1624790 Add connection check when decoding arrow chunks.
=> SNOW-1624790: Add connection check when decoding arrow chunks

version.go
=> PATCH: Bumped up GoLang connector PATCH version from 1.11.0 to 1.11.1

version.go
=> PATCH: Bumped up GoLang connector PATCH version from 1.11.1 to 1.11.2

auth.go, dsn_test.go
=> SNOW-1692674 Remove *.okta.com check from native Okta authenticator validation

azure_storage_client.go
SNOW-1732907 SnowflakeTransport configuration is not being passed throughout all of the azure storage communication. It might affect e.g proxy. This commit intends to fix this.
=> SNOW-1732907 Fix proxy configuration for Azure storage client

driver_ocsp_test.go, driver_test.go
SNOW-1759523 Fixes tests which got 404 instead of connection errors
=> SNOW-1759523 Fix 404 for test accounts

driver_test.go
NO-SNOW Please explain the changes you made here.
=> NO-SNOW Fix bogus hostname on Jenkins

arrow_chunk.go, connection.go, connection_util.go, ocsp.go
SNOW-1661955 Extend logs for QueryArrowStream
=> SNOW-1661955 extend logs for QueryArrowStream

README.md
=> SNOW-1756807: Add note about GCP regional endpoints

version.go
=> MINOR: Bumped up GoLang connector MINOR version from 1.11.2 to 1.12.0

doc.go
SNOW-1799603 Add some docs about using `WithHigherPrecision` in arrow batches mode.
=> SNOW-1799603 Add docs about using higher precision in arrow batches mode

.github/workflows/build-test.yml, .github/workflows/jira_close.yml, .github/workflows/jira_issue.yml, .github/workflows/snyk-issue.yml, .github/workflows/snyk-pr.yml
SNOW-1825712: Update GH actions versions
=> SNOW-1825712: Update GH actions versions

connection.go, connection_configuration.go, connection_configuration_test.go, doc.go, driver_test.go, dsn.go, dsn_test.go, ocsp.go, test_data/connections.toml, util.go, util_test.go
SNOW-1821505 Introduced disableOCSPChecks and deprecated insecureMode.
=> SNOW-1821505 Introduce disableOCSPChecks config option

version.go
=> PATCH: Bumped up GoLang connector PATCH version from 1.12.0 to 1.12.1

assert_test.go, driver_test.go
Added tests for WithRequestID and different sessions
=> Testing WithRequestID

arrow_chunk.go, arrow_test.go
SNOW-1802651 Fixes releasing Arrow record reader.
=> SNOW-1802651 Fix Arrow memory leak

Jenkinsfile
=> SNOW-1852300 use bptp-built tag for jenkins tests

version.go
=> NO-SNOW Bump driver version

auth.go, secure_storage_manager.go, secure_storage_manager_test.go
=> SNOW-1825790 Token cache refactor - v2

retry.go
=> rename retires to attempts in timeout error message

dsn.go, dsn_test.go
SNOW-1825500 Added config option for OAuth2
=> SNOW-1825500 Handle OAuth2 parameters in DSN

put_get_test.go
=> SNOW-1926861 Use subtests for running max lob size tests

Makefile, ci/image/scripts/entrypoint.sh, ci/scripts/execute_tests.sh
SNOW-1937440 Fix docker image after migration to alpine
=> SNOW-1937440 Fix docker image

auth.go, auth_oauth.go, auth_oauth_test.go, auth_test.go, ci/test.sh, dsn.go, dsn_test.go, test_data/wiremock/mappings/oauth2/client_credentials/invalid_client.json, test_data/wiremock/mappings/oauth2/client_credentials/successful_flow.json
SNOW-1917237 Implemented OAuth2 client_credentials flow
=> SNOW-1917237 Implement client_credentials flow

connection.go, connection_util.go, transaction.go, util.go, util_test.go
* Implement existing TODOs using context values
* See JIRA / Google doc for motivation and details
=> SNOW-1924252: Support internal flag

version.go
=> MINOR: Bumped up GoLang connector MINOR version from 1.13.0 to 1.13.1

auth_oauth.go, auth_test.go, ci/scripts/execute_tests.sh
SNOW-1825500 Added support for default Snowflake endpoints
=> Snow 1825500 oauth2 default endpoints support

arrow_test.go
=> NO-SNOW Fix TestArrowMemoryCleanedUp

structured_type_write_test.go
=> NO-SNOW Add additional test case for binding semistructured arrays

auth_oauth.go, auth_oauth_test.go
SNOW-1825500 Add browser timeout for OAuth authorization code flow
=> SNOW-1825500 Add browser timeout for OAuth authorization code flow

ocsp.go, ocsp_test.go
SNOW-2013198 Before we never cleared OCSP cache, so in case of contacting with multiple HTTPS hosts, this cache grew endlessly. Now it is regularly cleared.
=> SNOW-2013198 Clear OCSP cache regularly

.github/workflows/build-test.yml, auth.go, auth_oauth.go, auth_oauth_test.go, authexternalbrowser.go, ci/scripts/run_wiremock.sh, ci/test.bat, driver_ocsp_test.go, driver_test.go, dsn.go, errors.go, go.mod, go.sum, restful.go, restful_test.go, secure_storage_manager.go, test_data/wiremock/mappings/oauth2/authorization_code/invalid_code.json, test_data/wiremock/mappings/oauth2/authorization_code/successful_flow.json, test_data/wiremock/mappings/oauth2/client_credentials/successful_flow.json, test_data/wiremock/mappings/oauth2/login_request.json, test_data/wiremock/mappings/oauth2/login_request_with_expired_access_token.json, test_data/wiremock/mappings/select1.json, wiremock_test.go
SNOW-1825500 Implemented caching of access tokens for oauth
=> SNOW-1825500 Cache access token

version.go
=>  MINOR: Bumped up GoLang connector PATCH version from 1.13.1 to 1.13.2

auth.go, auth_oauth.go, auth_oauth_test.go, auth_test.go, errors.go, secure_storage_manager.go, secure_storage_manager_test.go, test_data/wiremock/mappings/oauth2/authorization_code/successful_flow_with_offline_access.json, test_data/wiremock/mappings/oauth2/refresh_token/invalid_refresh_token.json, test_data/wiremock/mappings/oauth2/refresh_token/successful_flow.json, test_data/wiremock/mappings/oauth2/refresh_token/successful_flow_without_new_refresh_token.json
SNOW-1825500 Added refreshing tokens to the OAuth flow.
=> SNOW-1825500 Implement OAuth2 refresh token flow

driver_ocsp_test.go, log.go, log_test.go, ocsp_test.go, secure_storage_manager_test.go
=> NO-SNOW Hide logger enabled flag behind mutex

auth_oauth.go
=> SNOW-1825500 Escape HTML body for OAuth

secret_detector.go, secret_detector_test.go
=> Snow 1825500 secret detector

.github/workflows/build-test.yml, Jenkinsfile, auth.go, ci/container/test_authentication.sh, ci/test.sh
SNOW-18254476 Readd experimental flag for PAT and OAuth
=> SNOW-18254476 Readd PrPr for PAT and OAuth

client_configuration.go, client_configuration_test.go, os_specific_posix.go, os_specific_windows.go, permissions_test.go, secure_storage_manager.go
SNOW-1155452 Fix race condition on perm checking for easy logging
=> SNOW-1155452 Fix race condition on perm checking for easy logging

version.go
=> PATCH: Bumped up GoLang connector PATCH version from 1.13.2 to 1.13.3

converter.go
NO-SNOW Fix array of times binding with custom format
=> NO-SNOW Fix array of times binding with custom format

arrow_test.go, converter.go, converter_test.go
SNOW-2052246 Fixed scan type when higher precision was enabled.
=> SNOW-2052246 Fix scan type for higher precision

doc.go
SNOW-1991292 Add oauth and PAT docs
=> SNOW-1991292 Add oauth and PAT docs

.github/workflows/build-test.yml, Jenkinsfile, auth.go, ci/container/test_authentication.sh, ci/test.sh
SNOW-1825500 Drop PrPr flag for oauth and pat
=> SNOW-1825500 Drop PrPr flag for oauth and pat

auth_with_pat_test.go
=> NO-SNOW add milliseconds to pat name in auth test

version.go
=> MINOR: Bumped up GoLang connector MINOR version from 1.13.3 to 1.14.0

auth_with_oauth_okta_authorization_code_test.go, authexternalbrowser.go
=> NO-SNOW Add more logging to authorization code flow

gcs_storage_client.go, gcs_storage_client_test.go
=> SNOW-2032700 Go driver support virtual-style domains(2)

version.go
=> PATCH: Bumped up GoLang connector PATCH version from 1.14.0 to 1.14.1

auth_wif.go, auth_wif_test.go, test_data/wiremock/mappings/wif/azure/http_error.json, test_data/wiremock/mappings/wif/azure/invalid_issuer_flow.json, test_data/wiremock/mappings/wif/azure/missing_issuer_claim.json, test_data/wiremock/mappings/wif/azure/missing_sub_claim.json, test_data/wiremock/mappings/wif/azure/non_json_response.json, test_data/wiremock/mappings/wif/azure/successful_flow_azure_functions.json, test_data/wiremock/mappings/wif/azure/successful_flow_azure_functions_custom_entra_resource.json, test_data/wiremock/mappings/wif/azure/successful_flow_azure_functions_no_client_id.json, test_data/wiremock/mappings/wif/azure/successful_flow_azure_functions_v2_issuer.json, test_data/wiremock/mappings/wif/azure/successful_flow_basic.json, test_data/wiremock/mappings/wif/azure/successful_flow_v2_issuer.json, test_data/wiremock/mappings/wif/azure/unparsable_token.json
=> SNOW-1902248: Add Azure WIF authentication support

crl.go, crl_test.go
=> SNOW-2117152 Add fail open mode to CRL implementation

version.go
=> MINOR: Bumped up GoLang connector MINOR version from 1.14.1 to 1.15.0

converter.go, structured_type.go
I found a couple of errors are ignored. I made them return error on error. I found them by static code analyzer and inspect them by myself to get sure. But I'm not familiar with gosnowflake so might mistake.
=> return error on error

assert_test.go, crl.go, crl_test.go, driver_test.go
SNOW-2117152 Implemented the main CRL algorithm.
=> SNOW-2117152 Implement CRL algorithm

ci/scripts/execute_tests.sh
=> NO-SNOW Fix output not produced for go test on Github Actions

auth_oauth.go, auth_oauth_test.go, auth_wif.go, azure_storage_client.go, client_test.go, connection.go, connection_test.go, crl.go, crl_test.go, driver_ocsp_test.go, driver_test.go, dsn.go, dsn_test.go, gcs_storage_client.go, ocsp.go, ocsp_test.go, s3_storage_client.go
SNOW-2117152 Enable CRLs to be used with connections.
=> SNOW-2117152 Add CRLs to DSN

auth.go
SNOW-2229753 Adds OAUTH_TYPE to CLIENT_ENVIRONMENT section of login request
=> SNOW-2229753 Add OAUTH_TYPE to CLIENT_ENVIRONMENT section

auth_test.go, auth_wif.go, auth_wif_test.go, ci/test_wif.sh
- Removed the autodetect feature
- Replaced debug logs with errors in the `createAttestation` methods
=> SNOW-2251273 Remove auto-detect feature in WIF

version.go
=> MINOR: Bumped up GoLang connector MINOR version from 1.15.0 to 1.16.0

errors.go
In case telemetry is disabled, this function still calls the expensive generateTelemetryExceptionData function.
This commit skips all unnecessary steps
unless telemetry is explicitly enabled. This should save quite some resources as
generateTelemetryExceptionData processes potentially large stack traces.
Testing:
No semantic changes, hence all existing tests should pass. No extra tests needed.
=> Avoid wasteful processing in exceptionTelemetry

crl_test.go
Sometimes Windows was too slow in closing ports.
=> NO-SNOW Fix flaky CRL tests (slow closing of Windows ports)

doc.go
This is a doc-only change, trying to address the challenges one of the users faced with a mixed-case database.
=> SNOW-2269982 update doc: quoted identifier, effect of validateDefaultParameters

.github/workflows/build-test.yml, auth_oauth_test.go, ci/scripts/execute_tests.sh, client_configuration_test.go, connection_configuration_test.go, connectivity_diagnosis_test.go, crl.go, crl_test.go, easy_logging_test.go, secure_storage_manager_test.go, test_utils_test.go
SNOW-2270004 Fixes driver startup when HOME env is not set.
=> SNOW-2270004 Fix panic on startup on missing HOME

chunk_downloader.go, chunk_test.go, multistatement_test.go, rows.go
SNOW-1646792 Fixes multistatement for large result sets (containing chunks)
=> SNOW-1646792 Fix multistatements for large result sets
